- cardano_node_tests/tests/test_pools.py
don't register and delegate stake address when not necessary (it's time
consuming)
> refactor pool tests

- cardano_node_tests/tests/test_staking.py
Add tests for rewards when pool owner stake address is unregistered and when pool reward address is unregistered.
> Add test_no_reward_stake_unregistered and test_reward_unregistered

- Makefile
- cardano_node_tests/tests/conftest.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/tests/test_update_proposal.py
- cardano_node_tests/utils/helpers.py
- cardano_node_tests/utils/parallel_run.py
- setup.cfg
* new parallel execution
* fixes for 1.20.0
* allure reports
> New parallel execution; allure reports

- cardano_node_tests/tests/conftest.py
Correctly detect running tests files
> Fix cluster_cleanup

- cardano_node_tests/tests/test_multisig.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
Test class instance is created for each test
> Cannot use id of instance for caching

- cardano_node_tests/utils/parallel_run.py
Also ranaming PARALLEL_LOG to SCHEDULING_LOG
> Correct relative path for SHEDULING_LOG

- cardano_node_tests/tests/test_staking.py
So waiting for resources is not counted towards test execution time
> Move all `cluster_manager.get` to fixtures

- cardano_node_tests/tests/test_staking.py
so the return value can be assigned and reused
> Return list instead of generator from _get_key_hashes

- cardano_node_tests/tests/conftest.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/utils/clusterlib_utils.py
- cardano_node_tests/utils/devops_cluster.py
- cardano_node_tests/utils/helpers.py
- cardano_node_tests/utils/logfiles.py
- cardano_node_tests/utils/parallel_run.py
* better searching for errors in logfiles after each test
* possibility to expect errors
> Search for errors; expect errors

- sync_tests/create_db.py
- sync_tests/sync_test.py
- sync_tests/write_values_to_db.py
changed the method of downloading the prebuilt node files
added new field into DB - chain_size
> updated sync_tests for tag 1.24.0

- sync_tests/sync_test.py
using `cardano-cli shelley` only for tags older than `1.24.0`
> CLI commands for different tags

- cardano_node_tests/tests/conftest.py
- cardano_node_tests/tests/test_multisig.py
- cardano_node_tests/utils/helpers.py
Enables us to skip tests based on node version
> Add possibility to check node version

- cardano_node_tests/cluster_scripts/allegra/cardano-node-bft1
- cardano_node_tests/cluster_scripts/allegra/cardano-node-bft2
- cardano_node_tests/cluster_scripts/allegra/cardano-node-bft3
- cardano_node_tests/cluster_scripts/allegra/cardano-node-pool1
- cardano_node_tests/cluster_scripts/allegra/cardano-node-pool2
- cardano_node_tests/cluster_scripts/allegra/config-bft1.json
- cardano_node_tests/cluster_scripts/allegra/config-bft2.json
- cardano_node_tests/cluster_scripts/allegra/config-bft3.json
- cardano_node_tests/cluster_scripts/allegra/config-pool1.json
- cardano_node_tests/cluster_scripts/allegra/config-pool2.json
- cardano_node_tests/cluster_scripts/allegra/start-cluster-hfc
- cardano_node_tests/utils/cluster_instances.py
- cardano_node_tests/utils/devops_cluster.py
So far metrics ports were shared by all nodes, so it didn't work on all but one.
> Metrics on all nodes

- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/utils/clusterlib.py
* Send funds from script address using the *all* script with zero skeys
* Send funds from script address using the *atLeast* script with no required witnesses
> Add test_multisig_no_required_atleast and test_multisig_empty_all

- cardano_node_tests/cluster_scripts/allegra/start-cluster-hfc
- cardano_node_tests/cluster_scripts/allegra/stop-cluster-hfc
- cardano_node_tests/cluster_scripts/mary/start-cluster-hfc
- cardano_node_tests/cluster_scripts/mary/stop-cluster-hfc
* better bash
* make stop-cluster scripts work from any path
> Cluster startup scripts enhancements

- cardano_node_tests/utils/parallel_run.py
> Handle cluster instance that failed to (re)start

- cardano_node_tests/utils/parallel_run.py
and refactor getting cluster instance.
> Fix marked tests scheduling

- cardano_node_tests/tests/test_transactions.py
See https://github.com/input-output-hk/cardano-node/pull/2226
Fixing test, moving it out of negative tests section.
> TX with no outputs can now be created in the cli

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/utils/clusterlib.py
as opposed to signing TX using witnesses.
> Add test for minting and burning tokens while signing TX using skeys

- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/utils/clusterlib.py
> Test for transfering funds from script addr using skyes

- cardano_node_tests/utils/clusterlib.py
and their UTXO have the same txhash#txix
> Fix txins when multiple different tokens in single TX

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/utils/clusterlib.py
Add tests that mint multiple different tokens in single transaction
> Tests that mint multiple different tokens in single transaction

- cardano_node_tests/utils/clusterlib.py
Instead of including all UTxOs with the given coin in the transaction, select only the UTxOs that are necessary to satisfy txouts, fees and deposits.
> Optimize UTxOs used for transactions

- cardano_node_tests/tests/test_transactions.py
Refactor invalid UTxO tests to reuse common functionality.
> Add test_invalid_lenght_utxo_hash

- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib.py
- cardano_node_tests/utils/helpers.py
> Fix spelling of "balance"

- Makefile
- cardano_node_tests/tests/conftest.py
Useful for providing Allure with a list of all runable tests.
> Ability to skip all tests

- cardano_node_tests/utils/parallel_run.py
The `instance_dir` was not created.
> Fix dev cluster setup

- cardano_node_tests/tests/test_staking.py
Tests two pools with the same reward address.
Closes https://github.com/input-output-hk/cardano-node-tests/issues/201
> Add test_2_pools_same_reward_addr

- cardano_node_tests/tests/test_native_tokens.py
Fee calculation is not precise enough.
> Fix FeeTooSmallUTxO error in minting tests

- cardano_node_tests/tests/test_native_tokens.py
> Tests for minting too many tokens

- cardano_node_tests/tests/test_configuration.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_metrics.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/utils/cluster_nodes.py
- cardano_node_tests/utils/cluster_scripts.py
- cardano_node_tests/utils/parallel_run.py
Moving scripts-related code to single class
> Cluster script python refactoring

- Makefile
- README.md
* create `make testnets` target
* update README.md with `make testnets` and description of available variables
> Make testnets

- README.md
- cardano_node_tests/cardano_cli_coverage.py
- setup.cfg
so it's on PATH in virtual env
> Install cli coverage script as a console script

- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/utils/clusterlib.py
- cardano_node_tests/utils/clusterlib_utils.py
Move general-enough functions to clusterlib
> Move several functions from clusterib_utils to clusterlib

- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_configuration.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_ledger_state.py
- cardano_node_tests/tests/test_metrics.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_protocol.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/tests/test_update_proposal.py
- cardano_node_tests/utils/cluster_management.py
- cardano_node_tests/utils/cluster_nodes.py
- cardano_node_tests/utils/clusterlib_utils.py
- cardano_node_tests/utils/helpers.py
- cardano_node_tests/utils/versions.py
Fixes and enhancements for node 1.26.0 release.
> 1.26.0 fixes

- cardano_node_tests/cluster_scripts/testnets/deregister-pools
- cardano_node_tests/cluster_scripts/testnets/start-cluster
- cardano_node_tests/cluster_scripts/testnets/stop-cluster
- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_configuration.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_ledger_state.py
- cardano_node_tests/tests/test_metrics.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_protocol.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/tests/test_update_proposal.py
- cardano_node_tests/utils/cluster_management.py
Another fixes and enhancements for node 1.26.0 release.
> 1.26.0 fixes2

- cardano_node_tests/tests/test_configuration.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_metrics.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib_utils.py
Changes related to https://github.com/input-output-hk/cardano-clusterlib-py/pull/1
> Rename last_block_* methods

- cardano_node_tests/tests/test_staking.py
... when running on env with no pools.
Skip tests that require reward when no reward was received.
> Skip shelley_qa tests that require pools

- cardano_node_tests/cluster_scripts/mary/genesis.spec.json
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
Set `minUTxOValue` to 1. Try to create an UTxO with no ada, just native tokens.
> minUTxOValue = 1

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/utils/clusterlib_utils.py
+ enhancements and fixes of the existing tests
> More native tokens tests

- cardano_node_tests/tests/test_native_tokens.py
Tests https://github.com/input-output-hk/cardano-node/issues/2337
> Test for non-ascii asset name

- cardano_node_tests/cluster_scripts/mary/start-cluster-hfc
- cardano_node_tests/cluster_scripts/testnets/start-cluster
- cardano_node_tests/cluster_scripts/testnets_nopools/start-cluster
- cardano_node_tests/tests/test_transactions.py
and
* small scripts enhancements
* ignore `TraceDidntAdoptBlocks` in "many UTxOs" transactions test
> Make sure Mary cluster is in Mary era

- nix/cardano-clusterlib.nix
- nix/sources.json
- shell.nix
* fix `nix-shell`
* add `cardano-clusterlib` python package
* use version 6.8.8 of `hypothesis` python package
> Fix nix-shell

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/utils/clusterlib_utils.py
CLI args changed in https://github.com/input-output-hk/cardano-node/pull/2547
> Fix scripts-related tests

- cardano_node_tests/testnet_cleanup.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib_utils.py
- nix/cardano-clusterlib.nix
- nix/sources.json
... that didn't make it to the chain.
https://github.com/input-output-hk/cardano-clusterlib-py/pull/11
> Use ClusterLib.submit_tx method that resends transactions

- cardano_node_tests/tests/test_transactions.py
Also check transaction in db when dbsync is available.
> Get txid from signed TX in addition to TX body

- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib_utils.py
- cardano_node_tests/utils/dbsync_utils.py
If db-sync is available, check transaction metadata in DB.
> Check TX metadata in DB

- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/utils/clusterlib_utils.py
- nix/cardano-clusterlib.nix
Closes https://github.com/input-output-hk/cardano-node-tests/issues/488
> Use `get_pool_params`

- cardano_node_tests/utils/clusterlib_utils.py
- cardano_node_tests/utils/dbsync_utils.py
* more detail txouts checks
* add txin checks
> More db-sync checks

- cardano_node_tests/utils/dbsync_utils.py
> More precise minting checks using dbsync

- cardano_node_tests/tests/test_governance.py
Test for sending more funds from treasury and reserve than available.
> Add `test_exceed_pay_stake_addr_from`

- .github/workflows/sync_test.yaml
adding the github actions workflow for sync tests in master (to be triggered from Actions UI)
> adding the github actions workflow for sync tests in master 

- Makefile
Set TEST_THREADS even when already set to empty value.
> Allow empty TEST_THREADS

- cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc
- cardano_node_tests/cluster_scripts/mary/start-cluster-hfc
> Add `AlonzoGenesisHash` to config files

- cardano_node_tests/tests/test_governance.py
Also add `--utxo-cost-per-word` check.
> Fix update proposals in Alonzo with Mary-era Tx

- cardano_node_tests/tests/test_governance.py
- cardano_node_tests/utils/dbsync_utils.py
* add support for pot transfers using MIR certificates
* add checks to tests
> Check pot transfers in db-sync

- cardano_node_tests/tests/test_cli.py
> Add test that uses `--whole-utxo`

- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/utils/dbsync_utils.py
Add db-sync checks for stake pool data.
Works with multiple owners.
> Add db-sync checks for stake pool data

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib_utils.py
- nix/default.nix
- requirements-dev.txt
- setup.cfg
Check more content of transaction files.
> Enhancements to `check_tx_view`

- cardano_node_tests/tests/test_staking.py
Add checks for epoch intervals for additional safety and more explicit
requirements.
> Optimize waiting for stake address deregistration

- cardano_node_tests/cluster_scripts/mary/config-bft1.json
- cardano_node_tests/cluster_scripts/mary/config-pool1.json
- cardano_node_tests/cluster_scripts/mary/config-pool2.json
- cardano_node_tests/cluster_scripts/mary/config-pool3.json
Issue https://github.com/input-output-hk/cardano-node/issues/2878 is
fixed.
> Reverting workaround for node issue #2878

- cardano_node_tests/tests/test_governance.py
Make it work with fractional prices.
> Update the price execution update proposal

- cardano_node_tests/tests/test_smart_contracts.py
Preparation for more plutus tests.
> Refactoring of test_txin_locking

- cardano_node_tests/tests/test_governance.py
- cardano_node_tests/utils/dbsync_utils.py
- nix/cardano-clusterlib.nix
Depends on https://github.com/input-output-hk/cardano-clusterlib-py/pull/34
> MIR cert tests using `transaction build`

- Makefile
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_staking.py
- pytest.ini
and possibility to specify marker expression when launching tests with
`make testnets`.
> Add "long" tests marker

- cardano_node_tests/utils/dbsync_utils.py
Addresses are not available for minting, only for tx outputs.
> Fix minting check using db-sync

- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib_utils.py
> Fix transaction view tests

- cardano_node_tests/tests/test_staking.py
Bug https://github.com/input-output-hk/cardano-node/issues/3074 is fixed.
> Enable withdrawals using `build` command

- Makefile
Also export `DbSyncAbortOnPanic`
> Simplify/refactor Makefile

- cardano_node_tests/tests/conftest.py
- cardano_node_tests/utils/dbsync_conn.py
- cardano_node_tests/utils/dbsync_queries.py
instead of using class with classmethods
> Refactor db-sync connection management into simple module

- cardano_node_tests/tests/test_delegation.py
Test state address "undelegation" by
* rewards withdrawal
* submitting address deregistration cert
* submitting address registration cert
all the above ^ in single transaction
> Add `test_undelegate`

- cardano_node_tests/tests/test_kes.py
Make the test future proof - calculate KES validity based on how long
will take local cluster to start.
> Make `test_expired_kes` work with Alonzo local cluster

- cardano_node_tests/utils/cluster_management.py
Detect if marked (grouped) tests are already finished and perform cleanup
so non-marked tests can run on the cluster instance.
> Fix cleanup after marked tests are finished

- cardano_node_tests/utils/logfiles.py
This is variant of error message that is already ignored.
> Ignore harmless error message

- cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc
Better waiting for expected eras and epochs.
> Improvements to alonzo start cluster shell script

- cardano_node_tests/tests/test_governance.py
Check that in one epoch, second update proposal cancels the first one.
> Add test for canceling update proposal

- cardano_node_tests/testnet_cleanup.py
- cardano_node_tests/tests/conftest.py
- cardano_node_tests/utils/testnet_cleanup.py
Perform cleanup at the end of a testing session:
* withdraw rewards
* deregister stake addresses
* return funds to faucet
> Automatically perform cleanup when running on testnet

- cardano_node_tests/tests/common.py
- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_configuration.py
- cardano_node_tests/tests/test_dbsync.py
- cardano_node_tests/tests/test_delegation.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_ledger_state.py
- cardano_node_tests/tests/test_mir_certs.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_mint_raw.py
- cardano_node_tests/tests/test_plutus_spend_build.py
- cardano_node_tests/tests/test_plutus_spend_raw.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_protocol.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transaction_fees.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/tests/test_update_proposals.py
- cardano_node_tests/utils/cluster_management.py
- cardano_node_tests/utils/clusterlib_utils.py
This helps to determine at what time each test started.
> Log test IDs in custer manager log file

- cardano_node_tests/utils/cluster_management.py
- cardano_node_tests/utils/cluster_nodes.py
- scripts/testnet_cleanup.sh
Also retain cluster instance number.
> Move `save_cluster_artifacts` to cluster manager

- Makefile
Add `NO_ARTIFACTS` env variable.
> Make it possible to not save artifacts

- Makefile
- cardano_node_tests/tests/delegation.py
- cardano_node_tests/tests/test_delegation.py
- cardano_node_tests/tests/test_staking.py
Tune `witness_override`s down to minimum required values.
> Tune `witness_override` down

- cardano_node_tests/tests/test_cli.py
Closes https://github.com/input-output-hk/cardano-node-tests/issues/487
> Test for `query stake-snapshot` command

- cardano_node_tests/tests/test_cli.py
Active stake can be lower than sum of stakes, as some pool may not be running and minting blocks.
> Fix stake snapshot test

- cardano_node_tests/tests/test_cli.py
> More testing of `test_stake_snapshot` is still needed

- cardano_node_tests/utils/logfiles.py
There can't be conflict between instances, so each can have it's own lock.
> Separate lock for each cluster instance

- cardano_node_tests/tests/test_blocks.py
- cardano_node_tests/utils/dbsync_queries.py
Closes https://github.com/input-output-hk/cardano-node-tests/issues/865
> Leadership schedule testing

- .buildkite/nightly_dbsync.sh
- .buildkite/nightly_dbsync.yml
The CI job was broken by commit 428f6a9
> Revert dbsync nightly job to previous working state

- cardano_node_tests/tests/test_transactions.py
Make `many_utxos` function more robust by repeating a transaction when "BadInputsUTxO" error happens.
> Repeat transaction when "BadInputsUTxO" error happens

- cardano_node_tests/tests/data/test_tx_metadata_both_tx.out
- cardano_node_tests/tests/test_transactions.py
It now shows collateral inputs.
> Change expected output of `transaction view`

- cardano_node_tests/tests/test_plutus_delegation.py
- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_spend_build.py
- cardano_node_tests/utils/dbsync_utils.py
- nix/cardano-clusterlib.nix
- setup.cfg
Use the `cardano-cli transaction build --calculate-plutus-script-cost` command.
> calculate cost of Plutus script and compare it with data from db-sync

- cardano_node_tests/tests/kes.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_staking.py
information on the related issue
> add new tests for command key-period-info

- cardano_node_tests/tests/data/test_tx_metadata_both_tx_body.out
- cardano_node_tests/tests/test_cli.py
See https://github.com/input-output-hk/cardano-node/pull/3617
> `transaction view` of tx file now prints signatures

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_mint_raw.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/test_staking.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/clusterlib_utils.py
- nix/cardano-clusterlib.nix
- setup.cfg
See https://github.com/input-output-hk/cardano-node/pull/3549
> Test incremental signing

- cardano_node_tests/tests/test_native_tokens.py
See https://github.com/input-output-hk/cardano-node/pull/2072
Closes https://github.com/input-output-hk/cardano-node-tests/issues/967
> Test syntax for specifying muti-asset values and txouts via CLI

- cardano_node_tests/tests/test_shelley_cddl.py
Tests presence of bug https://github.com/input-output-hk/cardano-node/issues/3688
> Smoke test for Shelley Tx with CDDL format

- .pre-commit-config.yaml
- Makefile
- cardano_node_tests/tests/conftest.py
- cardano_node_tests/tests/delegation.py
- cardano_node_tests/tests/test_plutus_delegation.py
- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_mint_raw.py
- cardano_node_tests/tests/test_plutus_spend_build.py
- cardano_node_tests/tests/test_plutus_spend_raw.py
On local system, following steps are needed:
```
make install
make init_lint
```
> Update linters and fix new reported issues

- .buildkite/nightly.sh
- .buildkite/nightly_dbsync.sh
- .github/workflows/regression-dbsync.yaml
- .github/workflows/regression.yaml
And other improvements:
* list of available cluster eras
* list of available Tx eras
* option to skip long running tests
> CDDL format selection in GH Actions

- .buildkite/db_sync_full_sync.yml
- .buildkite/db_sync_snapshot_restoration.yml
- .github/workflows/db_sync_full_sync.yaml
- .github/workflows/db_sync_snapshot_restoration.yaml
Add db-sync test workflows definitions for full sync and snapshot restoration - Buildkite and Github Actions
> Add db-sync test workflows definitions 

- .github/workflows/repo_lint.yaml
- .pre-commit-config.yaml
- requirements-dev.txt
* pre-commit autoupdate
* pin pylint version
* update github action
> Linting update

- cardano_node_tests/tests/plutus_common.py
- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_mint_raw.py
- cardano_node_tests/tests/test_plutus_spend_build.py
- cardano_node_tests/tests/test_plutus_spend_raw.py
* review execution cost for spending and minting plutus scripts
* compute required collateral
* review required funds
* fixes and impovements
> Use execution cost to compute required collateral

- cardano_node_tests/tests/test_pool_saturation.py
Also update interval fraction - the margin can increase slightly, but not by 100%.
> Increase pool oversaturation amount to "saturation amount * 2"

- cardano_node_tests/tests/test_plutus_mint_raw.py
\+ more precise test descriptions and comments
> Another test for checking that minting policy is executed only once

- .buildkite/nightly_upgrade.sh
- .buildkite/nightly_upgrade.yml
See https://buildkite.com/input-output-hk/cardano-node-tests-nightly-upgrade
> Nightly job for testing node upgrades

- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_spend_build.py
To make sure we haven't missed any test / test class.
> Global skips of "build" tests

- cardano_node_tests/utils/cluster_management.py
- cardano_node_tests/utils/logfiles.py
Don't clean error ignore files when test failed and cluster needs to be
restarted. In such cases the error condition may continue and the error
might get reported by unrelated tests.
> Fix errors ignoring when cluster needs restart

- cardano_node_tests/tests/test_transactions.py
See https://github.com/input-output-hk/cardano-node/issues/3913
> Workaround for too low minimum UTxO value

- cardano_node_tests/tests/test_kes.py
The opcert counter needs to be +1 from last used opcert in Babbage.
> Test `CounterOverIncrementedOCERT` error in Babbage

- cardano_node_tests/tests/data/plutus/v2/always-succeeds-spending.plutus
- cardano_node_tests/tests/plutus_common.py
- cardano_node_tests/tests/test_plutus_v2_spend_raw.py
- nix/cardano-clusterlib.nix
- setup.cfg
Depends on https://github.com/input-output-hk/cardano-clusterlib-py/pull/96 (CI will fail until this is merged)
> Add test for reference txin with Plutus V2

- cardano_node_tests/tests/plutus_common.py
- cardano_node_tests/tests/test_plutus_mint_raw.py
The collateral amount is limited using `--tx-total-collateral`.
> Try to mint with limited collateral

- cardano_node_tests/tests/test_delegation.py
- cardano_node_tests/tests/test_plutus_delegation.py
Esp. on testnets more time is sometimes needed.
> More time for actions that need to finish in same epoch

- cardano_node_tests/tests/test_blocks.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_protocol.py
- cardano_node_tests/tests/test_staking_no_rewards.py
All commands should work by now.
> Remove xfailures for "currently broken" commands

- cardano_node_tests/tests/test_protocol.py
See https://github.com/input-output-hk/cardano-node/issues/3883
> `query protocol-state` is still broken

- cardano_node_tests/tests/test_protocol.py
See https://github.com/input-output-hk/cardano-node/pull/4102
> Test `query protocol-state` with updated values

- cardano_node_tests/tests/test_plutus_mint_build.py
- cardano_node_tests/tests/test_plutus_mint_raw.py
For tests that use `anyone-can-mint.plutus` script.
> Plutus V2 versions of existing minting tests

- cardano_node_tests/tests/test_chain_transactions.py
- cardano_node_tests/tests/test_transactions.py
- cardano_node_tests/utils/cluster_management.py
Generate Txs in one loop and submit them in another to speed things up and allow more chained Txs in single block.
> More chained Txs in a block

- nix/cardano-clusterlib.nix
- nix/sources.json
- setup.cfg
> Update cardano-clusterlib-py requirement to 0.3.0rc7

- cardano_node_tests/tests/data/plutus/big.datum
- cardano_node_tests/tests/plutus_common.py
- cardano_node_tests/tests/test_plutus_v2_spend_build.py
block until https://github.com/input-output-hk/cardano-clusterlib-py/pull/108 is accepted
> check min UTxO value with inline datum

- cardano_node_tests/utils/tx_view.py
i.e. minting, withdrawal, certificates in addition to spending scripts that are already supported
> Support for rest of the types of reference scripts

- nix/cardano-clusterlib.nix
- setup.cfg
Fix for `StopIteration` exception in `get_pool_params`.
> Update to cardano-clusterlib 0.3.0rc12

- cardano_node_tests/utils/tx_view.py
Some of the features supported in master are not present in 1.35.2.
Plus cleanups, unifications, reporting improvements.
> Make `check_tx_view` compatible with 1.35.2

- cardano_node_tests/tests/test_plutus_v2_spend_build.py
depends of https://github.com/input-output-hk/cardano-node/pull/4204
> check that calculate-plutus-script-cost include script hash for reference scripts

- cardano_node_tests/tests/common.py
after https://github.com/input-output-hk/cardano-node/pull/4135 is fixed.
> New build command skipif

- cardano_node_tests/utils/dbsync_queries.py
- cardano_node_tests/utils/dbsync_utils.py
depends on: https://github.com/input-output-hk/cardano-node-tests/pull/1304
> dbsync: check reference scripts

- cardano_node_tests/tests/test_plutus_v2_spend_build.py
- cardano_node_tests/tests/test_plutus_v2_spend_raw.py
- cardano_node_tests/tests/test_scripts.py
There's a dedicated test `test_spend_reference_script` for both SimpleScriptV1 and SimpleScriptV2 in `test_scripts.py`.
> Test only with Plutus scripts

- cardano_node_tests/tests/test_plutus_spend_build.py
- cardano_node_tests/tests/test_plutus_v2_spend_build.py
- cardano_node_tests/tests/test_transactions.py
See
* https://github.com/input-output-hk/cardano-node/pull/4446
* https://github.com/input-output-hk/cardano-node/pull/4483
* https://github.com/input-output-hk/cardano-node/pull/4484
> Fixes for updated error messages in node master

- .github/workflows/db_sync_docker_sync_test.yaml
Smoke tests for `docker-compose` with and without flags on all supported environments.
> Add db-sync docker sync tests

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_shelley_cddl.py
- cardano_node_tests/tests/test_transactions.py
See https://github.com/input-output-hk/cardano-node/pull/4303
> Fixes needed after making CDDL format default

- README.md
- src_docs/source/test_results/nightly_system_tests.rst
- src_docs/source/test_results/node/tag_1_35_3.rst
- added explanations for the statuses of the tests
- removed the 'Publishing testing results' from the Readme 
- fixed the links for the sync tests from per tag results
> small changes to the github page

- cardano_node_tests/tests/test_plutus_delegation.py
dependent on this https://github.com/input-output-hk/cardano-clusterlib-py/pull/138
> Plutus v2 delegation with reference script build raw

- src_docs/source/contribute.rst
- src_docs/source/how-tos.rst
- src_docs/source/index.rst
- src_docs/source/process.rst
- src_docs/source/test_results.rst
> Fix "no title" in breadcrumbs navigation

- cardano_node_tests/tests/test_kes.py
to let the nodes re-connect correctly on fast-paced network.
> Restart all cluster nodes instead of only selected ones

- cardano_node_tests/tests/test_transactions.py
See https://github.com/input-output-hk/cardano-node/issues/4591
> XFAIL on node issue 4591

- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_transactions.py
- nix/cardano-clusterlib.nix
- setup.cfg
depends on: https://github.com/input-output-hk/cardano-node/issues/4459
and on clusterlib PR: https://github.com/input-output-hk/cardano-clusterlib-py/pull/145
> test new command query tx-mempool

- cardano_node_tests/tests/conftest.py
- cardano_node_tests/utils/configuration.py
Pytest metadata are used also in reports.
> Add more info to pytest metadata

- .buildkite/nightly_upgrade.sh
- .buildkite/nightly_upgrade_pytest.sh
- cardano_node_tests/tests/test_node_upgrade.py
Make it work with 1.35.3 -> 1.35.4 and protocol version 8.
> Update upgrade testing

- requirements-dev.txt
pylint==2.15.6 looks broken (astroid-error)
> Pin pylint version

- cardano_node_tests/tests/test_chain_transactions.py
Don't calculate ttl for every tx. It is too time consuming and we've seen `OutsideValidityIntervalUTxO` because of that.
> Speed up tx building with Shelley tx

- .github/regression.sh
- .github/workflows/regression-dbsync.yaml
- .github/workflows/regression.yaml
- .github/workflows/regression_reusable.yaml
- cardano_node_tests/cluster_scripts/babbage/start-cluster-hfc
- cardano_node_tests/cluster_scripts/babbage_fast/start-cluster-hfc
- cardano_node_tests/tests/conftest.py
- cardano_node_tests/utils/configuration.py
We can now run tests with
* legacy
* P2P
* mixed
> Support mixed topology

- .github/workflows/regression-dbsync.yaml
- .github/workflows/regression.yaml
Empty by default, but ready when there is a need to tests / set env variables.
> Add env files for regression CI jobs

- .github/workflows/nightly.yaml
- .github/workflows/nightly_alonzo_tx.yaml
- .github/workflows/nightly_dbsync.yaml
- .github/workflows/nightly_mary_tx.yaml
- .github/workflows/nightly_p2p.yaml
- .github/workflows/nightly_shelley_tx.yaml
- .github/workflows/regression-dbsync.yaml
- .github/workflows/regression.yaml
- .github/workflows/regression_reusable.yaml
See https://docs.github.com/en/actions/security-guides/automatic-token-authentication
> Use the automatic `GITHUB_TOKEN`

- .github/node_upgrade.sh
- .github/node_upgrade_pytest.sh
* step1 - legacy
* step2 - mixed
* step3 - p2p
> Use different network topologies in each step

- flake.lock
`nix flake lock --update-input cardano-node`
> Update cardano-node lock

- cardano_node_tests/tests/test_dbsync.py
On "fast" cluster it might be needed to wait one epoch for the record to appear in db.
> Wait for cost models to appear in db

- cardano_node_tests/tests/test_tx_negative.py
Testing node issue https://github.com/input-output-hk/cardano-node/issues/4863
> Tests for submitting basic Txs with wrong validity range

- cardano_node_tests/tests/delegation.py
- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_staking_no_rewards.py
- cardano_node_tests/tests/test_staking_rewards.py
- cardano_node_tests/utils/clusterlib_utils.py
needs: https://github.com/input-output-hk/cardano-clusterlib-py/pull/151
> replace deprecated 'query pool-params'

- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/tests_plutus/test_mint_negative_build.py
Related to: https://github.com/input-output-hk/cardano-node/issues/4619
> test mint token with name longer than allowed

- cardano_node_tests/tests/test_tx_negative.py
Try to build a Shelley era TX with an `--invalid-before` argument.
> Add `test_lower_bound_not_supported`

- cardano_node_tests/utils/dbsync_queries.py
- cardano_node_tests/utils/dbsync_utils.py
requires https://github.com/input-output-hk/cardano-clusterlib-py/pull/160
> check required signers on db-sync

- Makefile
- cardano_node_tests/tests/tests_plutus/conftest.py
- cardano_node_tests/tests/tests_plutus_v2/conftest.py
https://github.com/input-output-hk/cardano-node/issues/4924
> Disable all Plutus testing until node issue 4924 is resolved

- .github/CODEOWNERS
- CONTRIBUTING.md
- README.md
- src_docs/source/contribute/contributing.rst
Last steps needed for resolving https://github.com/input-output-hk/cardano-node-tests/issues/1471
> Repo Preparation for MBO, last steps

- cardano_node_tests/tests/test_scripts.py
See https://github.com/input-output-hk/cardano-node/pull/4763
> Remove simple script distinction

- cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py
- cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py
See https://github.com/input-output-hk/cardano-node/pull/3775
> Fix tests after changed error message

- cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py
- cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py
See https://github.com/input-output-hk/cardano-node/pull/4344
> Fix tests after removal of unnecessary validation of Data

- cardano_node_tests/tests/data/golden_payment.vkey
- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/tests_plutus/test_mint_negative_build.py
- cardano_node_tests/utils/clusterlib_utils.py
needs https://github.com/input-output-hk/cardano-clusterlib-py/pull/171
> check 'test address key-hash'

- cardano_node_tests/tests/data/golden_stake.vkey
- cardano_node_tests/tests/test_cli.py
needs https://github.com/input-output-hk/cardano-clusterlib-py/pull/173
> New tests for 'stake-address key-hash'

- src_docs/source/test_results/tag_tests.rst
> Add 1.35.7 to TOC; reverse sort TOC

- cardano_node_tests/cluster_scripts/babbage/start-cluster-hfc
- cardano_node_tests/cluster_scripts/babbage_fast/start-cluster-hfc
- cardano_node_tests/cluster_scripts/babbage_fast/template-config.json
- cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster-hfc
- cardano_node_tests/cluster_scripts/mainnet_fast/template-config.json
On master, `TestEnableDevelopmentNetworkProtocols` got renamed to `ExperimentalProtocolsEnabled`.
> Make sure correct setting name is used

- cardano_node_tests/tests/test_rollback.py
- scripts/test_rollbacks.sh
> Improve rollback testing

- cardano_node_tests/tests/test_configuration.py
Also don't wait for new epoch when not necessary.
> Fix `check_epoch_length` so there's enough time for tip update

- cardano_node_tests/tests/common.py
See https://github.com/input-output-hk/cardano-node/issues/5109
> Skip tests affected by node issue 5109

- .github/workflows/codeql.yml
Also skip when no python file was changed.
> Skip codeql action on PR merge

- cardano_node_tests/tests/data/golden_stake_pool.skey
- cardano_node_tests/tests/data/governance_poll.json
- cardano_node_tests/tests/test_governance.py
needs https://github.com/input-output-hk/cardano-clusterlib-py/pull/178
> Add tests to governance poll commands

- cardano_node_tests/tests/test_governance.py
- cardano_node_tests/utils/poll_utils.py
* full E2E test that create, answer and verify poll
* submit only Tx that need to be submitted
* verify both Tx body and signed Tx
* broaden boundaries in PBT
> Make improvements to SPO poll tests

- poetry.lock
- pyproject.toml
There's no functional change, the only changes are to package building. So this time nix doesn't need to get updated.
> Update clusterlib to 0.4.7 in poetry

- cardano_node_tests/tests/test_socket_path.py
Depends on https://github.com/input-output-hk/cardano-clusterlib-py/pull/181
> Tests for `--socket-path`

- cabal_build_tests/install-node.sh
- cabal_build_tests/run-fedora.sh
- cabal_build_tests/run-ubuntu.sh
Unify shell script conventions with the rest of shell scripts in the repo and fix minor issues.
> Small fixes and unifications of cabal build tests

- cardano_node_tests/cluster_scripts/babbage/start-cluster-hfc
See https://github.com/input-output-hk/cardano-node/issues/5233
> Workaround for node issue 5233

- cardano_node_tests/cluster_scripts/babbage/start-cluster-hfc
- cardano_node_tests/cluster_scripts/babbage/stop-cluster-hfc
- cardano_node_tests/cluster_scripts/babbage_fast/start-cluster-hfc
- cardano_node_tests/cluster_scripts/babbage_fast/stop-cluster-hfc
- cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster-hfc
- cardano_node_tests/cluster_scripts/mainnet_fast/stop-cluster-hfc
- cardano_node_tests/cluster_scripts/testnets/cardano-node-relay1
- cardano_node_tests/cluster_scripts/testnets/start-cluster
- cardano_node_tests/cluster_scripts/testnets/stop-cluster
- cardano_node_tests/utils/cluster_scripts.py
Also fixes submit-api on testnets.
> Improve cluster ports configuration

- cardano_node_tests/utils/helpers.py
* `wait_for`
* `get_cmd_path`
* `replace_str_in_file`
* `is_port_open`
> Remove helper functions that are no-longer used

- cardano_node_tests/cluster_management/manager.py
- cardano_node_tests/tests/test_cli.py
- cardano_node_tests/tests/test_env_network_id.py
- cardano_node_tests/tests/test_kes.py
- cardano_node_tests/tests/test_tx_negative.py
- cardano_node_tests/tests/tests_plutus/test_spend_raw.py
- cardano_node_tests/utils/logfiles.py
* fix seeking
* add ignore rules expiration
* refactoring
> Improve searching of log files for errors

- cardano_node_tests/utils/blockers.py
The log is available in Allure report and so it is easy to follow the URL.
> Log GH issue URL

- cardano_node_tests/tests/test_governance.py
needs https://github.com/input-output-hk/cardano-clusterlib-py/pull/186/files
> Check governance poll required signers on dbsync

- cardano_node_tests/tests/delegation.py
- cardano_node_tests/tests/test_staking_rewards.py
- cardano_node_tests/utils/dbsync_check_tx.py
- cardano_node_tests/utils/dbsync_types.py
- cardano_node_tests/utils/dbsync_utils.py
Extract `check_tx` into separate module and split it into several more focused functions.
Extract also common data types into separate module.
> Refactor dbsync utils

- cardano_node_tests/tests/test_governance.py
See https://github.com/input-output-hk/cardano-node/issues/5182
> Add test for node issue 5182

- cardano_node_tests/tests/test_cli.py
See https://github.com/input-output-hk/cardano-node/issues/5324
> XFAIL on node issue 5324

- cardano_node_tests/tests/test_cli.py
needs: https://github.com/input-output-hk/cardano-clusterlib-py/pull/187
> Add tests for 'query slot-number'

- cardano_node_tests/tests/test_cli.py
> The node issue 5324 is not fixed in master

- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_staking_no_rewards.py
- cardano_node_tests/tests/test_tx_basic.py
- cardano_node_tests/tests/tests_plutus/spend_build.py
- cardano_node_tests/tests/tests_plutus/spend_raw.py
- cardano_node_tests/tests/tests_plutus/test_mint_build.py
- cardano_node_tests/tests/tests_plutus/test_mint_raw.py
Named tuple has `_replace` member, pylint is wrong.
> Ignore wrong pylint error

- cardano_node_tests/tests/test_cli.py
See https://github.com/input-output-hk/cardano-cli/issues/49
> Add blocker for cardano-cli issue 49

- poetry.lock
This resolves advisory ttps://github.com/advisories/GHSA-jm77-qphf-c4w8
> Update cryptography package to 41.0.3

- .github/regression.sh
- README.md
- cardano_node_tests/cluster_management/manager.py
- cardano_node_tests/tests/conftest.py
- cardano_node_tests/utils/configuration.py
> Add possibility to keep clusters running

- cardano_node_tests/tests/plutus_common.py
https://github.com/input-output-hk/plutus-apps/issues/1107
> Add blocker for plutus-apps issue 1107

- cardano_node_tests/tests/common.py
- cardano_node_tests/tests/test_addr_registration.py
- cardano_node_tests/tests/test_delegation.py
https://github.com/input-output-hk/cardano-cli/issues/268
> Match cardano-cli issue 268

- cardano_node_tests/tests/tests_plutus/test_delegation.py
* https://github.com/input-output-hk/cardano-cli/issues/297
* https://github.com/input-output-hk/cardano-cli/issues/299
> XFAIL on blocking delegation issues

- cardano_node_tests/tests/tests_plutus/test_delegation.py
Add test that registers and deregisters Plutus script stake address.
> Add `test_register_deregister`

- cardano_node_tests/tests/tests_plutus/test_delegation.py
Add a test that registers, delegates and deregisters a Plutus script stake address.
> Add `test_register_delegate_deregister`

- cardano_node_tests/tests/test_blocks.py
See https://github.com/input-output-hk/cardano-api/issues/269
> Xfail on cardano-api GH 269

- .github/node_upgrade_pytest.sh
Also cleanup comments and move code around a bit.
> Add checks that nodes were restarted correctly

- cardano_node_tests/tests/tests_plutus/test_delegation.py
https://github.com/input-output-hk/cardano-node-tests/pull/new/match_new_297
> Match also the new errors from cardano-cli 297 issue

- cardano_node_tests/cluster_scripts/babbage/start-cluster
- cardano_node_tests/cluster_scripts/babbage_fast/start-cluster
- cardano_node_tests/cluster_scripts/conway/start-cluster
- cardano_node_tests/cluster_scripts/conway_fast/start-cluster
- cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Workaround for https://github.com/input-output-hk/cardano-cli/issues/472
> Use fixed fee in testnet start scripts

- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/utils/clusterlib_utils.py
We'll need to register multiple DReps in single Tx
> Make DRep registration more reusable

- .github/workflows/nix_smoke.yaml
- .github/workflows/regression_reusable.yaml
- .github/workflows/upgrade_reusable.yaml
Reverts input-output-hk/cardano-node-tests#2059
We are now getting `error: unrecognised flag '--recreate-lock-file'`
> Revert "Bump cachix/install-nix-action from 23 to 24"

- cardano_node_tests/cluster_scripts/conway/genesis.conway.spec.json
- cardano_node_tests/cluster_scripts/conway_fast/genesis.conway.spec.json
Update values to enable us to enact actions and check deposits.
> Update conway genesis values

- cardano_node_tests/tests/tests_conway/test_committee.py
It was missing deposit handling and previous action args.
> Fix test that updates commitee action

- .github/source_dbsync.sh
> dbsync: Add possibility to skip indexes creation

- cabal_build_tests/fedora/Dockerfile
- cabal_build_tests/install-node.sh
Tested on both `Ubuntu` and `Fedora` with:
```
./run-fedora.sh -t tag -o "8.7.0-pre"
./run-ubuntu.sh -t tag -o "8.7.0-pre"
```
> Update cabal tests

- cardano_node_tests/tests/tests_conway/test_voting.py
https://github.com/IntersectMBO/cardano-ledger/issues/4001
> Test ledger issue 4001

- cardano_node_tests/tests/tests_conway/test_committee.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/tests/tests_conway/test_voting.py
- src_docs/source/chang_user_stories_template.md
See User Story IDs in https://github.com/IntersectMBO/cardano-test-plans/blob/main/docs/user-stories/02-cardano-cli.md
> Unify CLI User Story IDs

- cardano_node_tests/tests/test_staking_no_rewards.py
A stake address registration/deregistration deposit amount is required in Conway+
> Update test_staking_no_rewards.py to work with conway

- cardano_node_tests/tests/tests_plutus/test_mint_negative_build.py
Tests in this file should all run also in env where only PlutusV1 is supported.
> Use PlutusV1 scripts

- cardano_node_tests/tests/test_delegation.py
> Fix signing_key_files for register stake address

- cardano_node_tests/tests/plutus_common.py
- cardano_node_tests/tests/tests_plutus_v2/test_mint_build.py
- cardano_node_tests/tests/tests_plutus_v2/test_mint_raw.py
needs https://github.com/input-output-hk/cardano-clusterlib-py/pull/237
> Update PlutusV2 mint tests to work with PlutusV3 reference scripts

- cardano_node_tests/tests/tests_conway/test_info.py
CIP59
As a Stakeholder I want the transaction ID and index of the transaction that submits the governance action to the chain to serve as the governance action ID so that this ID shall would be used for casting votes.
> Update Conway CIP59 coverage

- cardano_node_tests/tests/tests_conway/test_pparam_update.py
CIP060
> As a Stakeholder I want each vote transaction to consist of the following elements:
> 
> a governance action ID
> a role (Constitutional Committee member, DRep, or SPO)
> a governance credential witness for the role
> an optional anchor for information relevant to the vote (as defined above)
> a 'Yes'/'No'/'Abstain' vote.
> Update Conway CIP60 coverage

- cardano_node_tests/tests/tests_conway/test_committee.py
CIP067
> As a Stakeholder I want new votes on a governance action to override any previous votes for the same credential and role so that individuals could change their minds.
> Update Conway CIP67 coverage

- cardano_node_tests/tests/tests_conway/test_committee.py
> As an Ada holder, I want the system to automatically expire committee members that have reached their term, so that only active committee members can vote.
> Check user story CIP011

- cardano_node_tests/tests/tests_conway/test_constitution.py
> **As** any persona, **I want** to query the on-chain constitution, **so that** I can know the url where it is stored and the document hash so that I can verify authenticity.
> Check user story CLI036

- cardano_node_tests/tests/tests_conway/test_constitution.py
- src_docs/requirements_mapping.json
> **As** a Governance actor creating a Update to the constitution GA, **I want** to include an anchor to the Constitution and an optional script hash of the proposal policy.
> Link requirement CIP031c

- cardano_node_tests/tests/tests_conway/test_committee.py
- cardano_node_tests/tests/tests_conway/test_pparam_update.py
- cardano_node_tests/utils/governance_utils.py
- src_docs/requirements_mapping.json
> **As** a Stakeholder **I want** unregistered stake to be treated as an abstain vote **so that** it should not count towards the active voting stake.
> Test user story CIP064

- cardano_node_tests/tests/tests_conway/test_no_confidence.py
> **As** a Stakeholder **I want** ratified actions to be automatically enacted at the next epoch boundary.
> Link user story CIP057

- cardano_node_tests/tests/tests_conway/test_committee.py
- cardano_node_tests/tests/tests_conway/test_constitution.py
- cardano_node_tests/tests/tests_conway/test_info.py
- cardano_node_tests/tests/tests_conway/test_no_confidence.py
- cardano_node_tests/tests/tests_conway/test_pparam_update.py
- cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
- src_docs/requirements_mapping.json
> **As** a Stakeholder **I want** all governance actions, except for Treasury withdrawals and Infos, to include the governance action ID of the most recently enacted action of the same type **so that** accidental clashes between actions can be prevented.
We don't cover Hard-Fork Initiation action yet.
> Link user story CIP054

- cardano_node_tests/tests/tests_conway/test_no_confidence.py
- cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
- src_docs/requirements_mapping.json
> **As** a Stakeholder **I want** the governance state section of the ledger to track the progress of governance actions to include: capturing votes, tracking the expiration epoch, and other relevant information until the actions are either ratified or expired.
> Link CIP069 user story

- cardano_node_tests/tests/reqs_conway.py
Useful for orientation of what part is still missing coverage.
> Add brief comment to internal requirements

- cardano_node_tests/tests/issues.py
- cardano_node_tests/utils/blockers.py
- cardano_node_tests/utils/versions.py
It was useless, even harmful when latest version info was not updated on time.
> Remove `check_on_devel`

- cardano_node_tests/tests/test_blocks.py
We want the original node to have time to forge blocks.
> Wait for at least the middle of epoch

- cardano_node_tests/tests/reqs_conway.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/utils/governance_utils.py
Check that delegated stake does not count towards the active voting stake for inactive DReps.
> Add more checks for inactive DReps stake

- cardano_node_tests/tests/issues.py
- cardano_node_tests/tests/test_tx_negative.py
https://github.com/IntersectMBO/cardano-cli/issues/796
> Xfail on CLI issue 796

- cardano_node_tests/tests/issues.py
- cardano_node_tests/tests/test_cli.py
https://github.com/IntersectMBO/cardano-cli/issues/799
> Xfail on CLI issue 799

- cardano_node_tests/tests/issues.py
- cardano_node_tests/tests/tests_plutus/test_spend_datum_build.py
https://github.com/IntersectMBO/cardano-cli/issues/800
> Xfail on CLI issue 800

- .github/env_nightly_conway_bootstrap
- .github/env_nightly_conway_cc
- .github/env_nightly_conway_nocc
Use cardano-cli with fix for https://github.com/IntersectMBO/cardano-cli/issues/825
> Temporarily use cardano-cli with fixes for Conway for nightly tests

- cardano_node_tests/tests/tests_conway/test_committee.py
based on https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1720122122984309
> Fix ConwayCommitteeIsUnknown error in test_committee file

- cardano_node_tests/tests/test_dbsync.py
PlutusV2 cost model can have variable length.
> Fix `test_cost_model` test on Conway

- cardano_node_tests/tests/test_staking_rewards.py
Let's see if it works: 
- Conway: https://github.com/IntersectMBO/cardano-node-tests/actions/runs/10385034165
- Babbage: https://github.com/IntersectMBO/cardano-node-tests/actions/runs/10385473822
> Fix test_reward_addr_delegation

- .github/source_dbsync.sh
Building dbsync from source or using nix takes a lot of disk space.
> Add support for downloading dbsync binary

- cardano_node_tests/utils/dbsync_queries.py
- cardano_node_tests/utils/dbsync_types.py
- cardano_node_tests/utils/dbsync_utils.py
* enable pydantic validation
* fix issues found by pydantic
> Validate db data with Pydantic

- .github/source_dbsync.sh
- Introduced `file_is_available` function to check if a URL is accessible.
- Automatically set `DBSYNC_TAR_URL` if `DBSYNC_REV` is a version number.
- Validate the constructed URL before using it.
- Ensure the script uses the tarball URL only if it is available.
> Add URL availability check for DBSYNC_TAR_URL

- cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
- Introduced a new fixture `cluster_use_governance_lock_treasury` to mark governance as "in use" and lock the treasury pot.
- Added `pool_user_ug_treasury` fixture to create a pool user for the "use governance, lock treasury" test setup.
- Updated `test_enact_treasury_withdrawals` to use the new fixtures.
> feat(treasury): add treasury lock for withdrawal tests

- .github/env_nightly_dbsync_pv10
- .github/env_nightly_pv10
- .github/workflows/nightly_dbsync_pv10.yaml
- .github/workflows/nightly_pv10.yaml
- Add environment configuration for nightly dbsync PV10
- Add environment configuration for nightly PV10
- Create nightly_dbsync_pv10.yaml workflow
- Create nightly_pv10.yaml workflow
- Schedule workflows to run at specified times
> feat(ci): add nightly workflows for Conway PV10

- cardano_node_tests/tests/tests_conway/test_treasury_donation.py
Split `test_transfer_treasury_donation` into two tests:
- parametrized `test_transfer_treasury_donation` smoke test that doesn't check treasury balance
- `test_dbsync_transfer_treasury_donation` test that crosses 2 epoch boundaries and checks treasury balance using db-sync
> feat(treasury): split treasury donation test

- cardano_node_tests/tests/tests_plutus_v2/test_mint_build.py
Refactor the minting test to always use reference scripts instead of parametrizing the use of reference scripts. The script file minting is sufficiently tested in
`tests_plutus.test_mint_build.test_minting_one_token`
- Removed the `use_reference_script` parameter.
- Updated assertions and expected fees accordingly.
> feat(tests): update minting test to always use reference script

- cardano_node_tests/tests/test_chain_transactions.py
Refactor the test_tx_chaining to handle cases where a transaction is removed from the mempool without making it to the blockchain. This ensures the whole chain of transactions is not disrupted by repeating the process up to three times if necessary.
> feat: improve tx chaining test robustness

- cardano_node_tests/tests/tests_conway/test_pparam_update.py
- Added `TestLegacyProposals` class to test legacy update proposals in Conway.
- Added tests to submit and build legacy update proposals, expecting failure as they are not supported in Conway.
> feat(tests): add legacy proposal tests for Conway

- cardano_node_tests/tests/test_native_tokens.py
Added additional funds to the mint address in the TestMinting class to ensure sufficient balance for minting operations.
> feat(tests): add more funds to mint address in TestMinting

- scripts/test_rollbacks.sh
Updated the rollback script to use the conway_fast directory instead of babbage_fast.
> feat(scripts): update rollback script to use conway_fast

- cardano_node_tests/cluster_scripts/conway/start-cluster
- cardano_node_tests/cluster_scripts/conway_fast/start-cluster
Added POOL_COST variable to make the pool cost configurable in both conway and conway_fast cluster scripts. Updated the pool cost parameter to use the new variable.
> feat(cluster): make pool cost configurable

- cardano_node_tests/tests/test_blocks.py
Ensure reconfiguration finishes within a single epoch and take submission delay into account when restarting node services.
> fix(tests): ensure reconfiguration finishes within a single epoch.

- cardano_node_tests/utils/governance_setup.py
Caller needs to obtain a lock before attempting governace setup. We no longer depend on governance state file existence.
> refactor(governance): make governance setup more robust

- cardano_node_tests/cluster_scripts/conway/start-cluster
- Introduced PV10 environment variable to enable protocol version 10.
- Implemented hard fork proposal submission and voting for PV10.
> feat(cluster): add support for protocol version 10 to HF cluster

- cardano_node_tests/cluster_scripts/conway/start-cluster
- cardano_node_tests/cluster_scripts/conway_fast/start-cluster
- cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Refactor the deposit calculations in cluster scripts to improve readability and maintainability. Extracted key and pool deposit values from genesis files and simplified the arithmetic operations for needed amounts.
> feat(cluster): refactor deposit calculations

- cardano_node_tests/cluster_scripts/conway/cardano-node-bft1
- cardano_node_tests/cluster_scripts/conway/run-cardano-submit-api
- cardano_node_tests/cluster_scripts/conway/template-cardano-node-pool
- cardano_node_tests/cluster_scripts/conway_fast/cardano-node-bft1
- cardano_node_tests/cluster_scripts/conway_fast/run-cardano-submit-api
- cardano_node_tests/cluster_scripts/conway_fast/template-cardano-node-pool
- cardano_node_tests/cluster_scripts/mainnet_fast/cardano-node-bft1
- cardano_node_tests/cluster_scripts/mainnet_fast/run-cardano-submit-api
- cardano_node_tests/cluster_scripts/mainnet_fast/template-cardano-node-pool
This commit updates the startup messages for cardano-node and cardano-submit-api scripts to include the process ID (PID). This enhancement helps in better tracking and debugging of running processes by providing the PID in the log messages.
> feat: add PID to startup messages for better tracking

- .github/node_upgrade_pytest.sh
- cardano_node_tests/tests/test_node_upgrade.py
- Add NETWORK_MAGIC export to node_upgrade_pytest.sh
- Modify genesis file handling in step1 and step2
- Add delay for Tx submission and chain sync checks
- Update test_node_upgrade.py to handle new serialization format
> feat: update node upgrade script and test

- src_docs/source/test_results/node/tag_10_1_1.rst
- src_docs/source/test_results/tag_tests.rst
- Added new file `tag_10_1_1.rst` with regression and other test results
- Updated `tag_tests.rst` to include the new test results file
- Included links to release notes, tag commits, and detailed test results
- Documented new issues and breaking changes in the release
> feat(docs): add test results for tag 10.1.1

- src_docs/source/test_results/node/tag_10_1_2.rst
- src_docs/source/test_results/tag_tests.rst
- Added new file `tag_10_1_2.rst` with test results for node tag 10.1.2.
- Updated `tag_tests.rst` to include the new test results file.
- Documented regression testing, other testing, and release testing checklist for the new tag.
> feat(docs): add test results for node tag 10.1.2

- cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
- Introduce `TestMIRCerts` class for testing MIR certificates.
- Parameterize `test_mir_certificates` to test different MIR cert scenarios.
- Update assertions to check for specific error messages related to MIR certs.
> feat(tests): add MIR certificates tests for Conway+ eras

- cardano_node_tests/utils/governance_setup.py
Added a check for DRep stake distribution in the governance setup process. This ensures that the DRep stake distribution is properly setup when the protocol version is 10 or higher.
> feat(governance): add DRep stake distribution check

- .github/node_upgrade.sh
- .github/regression.sh
- .github/workflows/regression_reusable.yaml
- .github/workflows/upgrade_reusable.yaml
- Improve log grouping by making all CI output part of some group.
- Rename `_cleanup_testnet` to `_cleanup_testnet_on_interrupt` for clarity.
> feat(ci): make all CI output part of group

- .github/regression.sh
GitHub Actions don't group output precisely. Another attempt to make the output look good.
> feat(ci): another attempt for better output grouping

- .github/node_upgrade.sh
- .github/regression.sh
Updated the group names in node_upgrade.sh and regression.sh to better reflect the teardown process and artifact collection. This improves clarity in the CI logs.
> feat: update teardown & artifacts group names in GHA

- .github/stop_cluster_instances.sh
- Add echo statement to indicate stopping of cluster instances
- Suppress error messages from supervisord_stop script
> feat: improve stop_cluster_instances.sh script

- .github/setup_venv.sh
Updated the virtual environment directory path from .env to .venv in the setup_venv.sh script to follow standard naming conventions.
> chore: update venv directory path

- .github/node_upgrade.sh
- .github/regression.sh
- .github/workflows/regression_reusable.yaml
- .github/workflows/upgrade_reusable.yaml
Enhanced CI output with icons for better readability.
> feat(ci): enhance test run logs with icons

- cardano_node_tests/tests/test_scripts.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/tests/tests_plutus_v2/test_spend_build.py
- Adjusted witness_count_add in test_scripts.py for better accuracy.
- Increased funding amount in test_drep.py.
- Updated expected_fee_redeem in test_spend_build.py to reflect fee on Preview.
> fix(tests): various fixes needed for Preview

- cardano_node_tests/tests/tests_conway/test_drep.py
- Updated `get_custom_drep` to `create_drep` for DRep creation
- Improved assertions for vote delegation checks
> feat(tests): update delegation test for DRep retirement

- cardano_node_tests/utils/logfiles.py
Added a new function `find_msgs_in_logs` to search for messages in log files based on a given regex pattern. This function supports seeking from a specific offset and timestamp, and can return either all matching lines or just the first match.
> feat(utils): add function to find messages in logs

- cardano_node_tests/utils/cluster_scripts.py
Updated the webserver command to bind to 127.0.0.1 for better security.
> fix(cluster_scripts): bind webserver to localhost

- cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
- Added a version check for CLI error handling in the treasury withdrawals test.
- Modified to use transaction build-raw command.
> feat(treasury_withdrawals): add version check for CLI error

- .github/env_nightly_cli
- .github/workflows/nightly_cli.yaml
- src_docs/source/test_results/nightly_system_tests.rst
- Add .github/workflows/nightly_cli.yaml for nightly CLI tests
- Add .github/env_nightly_cli file with environment variables
- Update src_docs/source/test_results/nightly_system_tests.rst with nightly CLI test results and badge
> feat: add nightly CLI workflow

- cardano_node_tests/tests/test_scripts.py
Add a new test `test_stake_keys_multisig_all` that uses stake keys for witnessing multisig Tx instead of payment keys.
> feat(tests): add multisig test using stake keys

- cardano_node_tests/tests/test_addr_registration.py
- Add test for registering a multisig stake address while missing either a script or a signing key.
- Expect failure in both scenarios.
- Scenario 1: Build a Tx with the registration certificate, without passing the script to the transaction build command.
- Scenario 2: One signing key is missing when witnessing the Tx.
> feat(tests): add incomplete multisig stake addr registration test

- cardano_node_tests/tests/common.py
- cardano_node_tests/tests/test_chain_transactions.py
- cardano_node_tests/tests/test_governance.py
- cardano_node_tests/tests/test_tx_metadata.py
- cardano_node_tests/tests/test_update_proposals.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/tests/tests_conway/test_guardrails.py
- cardano_node_tests/tests/tests_conway/test_pparam_update.py
- cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
- Moved get_payment_addr function to common.py for reuse
- Updated test files to use the common get_payment_addr function
- Removed redundant get_payment_addr implementations from test files
- Ensured caching and funding logic is consistent across tests
> feat: refactor get_payment_addr function

- cardano_node_tests/tests/common.py
- cardano_node_tests/tests/test_addr_registration.py
- cardano_node_tests/tests/test_delegation.py
- cardano_node_tests/tests/test_mir_certs.py
- cardano_node_tests/tests/test_pools.py
- cardano_node_tests/tests/test_tx_fees.py
- cardano_node_tests/tests/test_tx_negative.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/tests/tests_plutus/test_spend_build.py
- cardano_node_tests/tests/tests_plutus/test_spend_raw.py
- cardano_node_tests/utils/clusterlib_utils.py
- Added `get_pool_users` function to create and fund multiple pool users.
- Added `get_pool_user` function to create and fund a single pool user.
- Updated tests to use the new `get_pool_users` and `get_pool_user` functions.
- Removed redundant code for creating and funding pool users in tests.
- Improved consistency and reusability of pool user creation and funding.
> feat: add get_pool_users and get_pool_user functions

- cardano_node_tests/cluster_management/cluster_getter.py
- cardano_node_tests/cluster_management/netstat_tools.py
- Added `get_netstat_conn` to fetch netstat connections
- Refactored `get_netstat_out` to `get_netstat_listen`
- Updated `kill_old_cluster` to use new netstat functions
> feat: add netstat connection listing and refactor tools

- cardano_node_tests/tests/test_reconnect.py
- cardano_node_tests/tests/test_staking_rewards.py
- cardano_node_tests/tests/test_tx_mempool.py
- cardano_node_tests/tests/tests_plutus/spend_build.py
- cardano_node_tests/tests/tests_plutus/spend_raw.py
- cardano_node_tests/tests/tests_plutus_v2/spend_build.py
- cardano_node_tests/tests/tests_plutus_v2/spend_raw.py
- cardano_node_tests/utils/cluster_nodes.py
- cardano_node_tests/utils/dbsync_utils.py
- cardano_node_tests/utils/governance_utils.py
- pyproject.toml
- src_docs/source/conf.py
- Added `PERF` to ruff linting rules in `pyproject.toml`
- Refactored code to comply with new performance rules
- Updated exception handling to include `# noqa: PERF203`
- Optimized list comprehensions and `extend` usage
> feat: enable performance checking with ruff

- cardano_node_tests/utils/dbsync_utils.py
Fix the error and simlify rewards records creation.
- Replaced manual list extension with itertools.chain for querying rewards
- Combined reward and reward_rest queries into a single chain
- Updated return statement to use address directly
> fix: fix IndexError when getting address

- cardano_node_tests/cluster_management/cluster_management.py
- cardano_node_tests/cluster_management/manager.py
- cardano_node_tests/tests/common.py
- cardano_node_tests/tests/test_mir_certs.py
- cardano_node_tests/tests/test_native_tokens.py
- cardano_node_tests/tests/test_tx_basic.py
- cardano_node_tests/tests/tests_conway/conway_common.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- cardano_node_tests/tests/tests_plutus/test_mint_build.py
- cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py
- cardano_node_tests/utils/governance_setup.py
- Added type annotations to FixtureCache class and its usage.
- Updated cache_fixture method to use generic type FixtureCache[T].
- Improved type safety by replacing tp.Any with specific types.
- Modified test files to handle the updated FixtureCache type.
> feat: add type annotations to FixtureCache

- cardano_node_tests/cluster_management/cluster_getter.py
- cardano_node_tests/cluster_management/common.py
- cardano_node_tests/cluster_management/manager.py
- cardano_node_tests/cluster_management/status_files.py
This refactor moves the handling of status files to a new dedicated module called status_files. This change improves the code organization and separation of concerns by isolating the status file operations into their own module.
> refactor: Move status files handling to a separate module

- cardano_node_tests/tests/issues.py
- cardano_node_tests/tests/tests_plutus/test_delegation.py
- Added a new issue handler for CLI issue 1023 in `issues.py`.
- Updated `test_delegation.py` to handle the new issue when the budget is overspent and CLI version is 10.2.0.0 or higher.
> feat(tests): add issue 1023 handling in Plutus tests

- cardano_node_tests/utils/logfiles.py
- Introduce BUFFER_SIZE constant for reading log files in chunks
- Modify _search_log_lines to read files in chunks using BUFFER_SIZE
- Preserve line endings while reading chunks
- Maintain look_back_buf for error look back functionality
> feat(logfiles): optimize log search with buffered reading

- flake.nix
Updated the nixpkgs input in flake.nix from nixos-24.05 to nixos-24.11.
> chore: update nixpkgs to nixos-24.11

- cardano_node_tests/tests/tests_conway/conway_common.py
- cardano_node_tests/tests/tests_conway/test_committee.py
Implemented `test_invalid_cc_member_vote` to test voting with an invalid CC member, expecting failure scenarios.
> feat(tests): add invalid CC member vote test

- cardano_node_tests/utils/logfiles.py
Refactor log file reading to process in chunks, improving efficiency. Updated docstrings for better clarity and added detailed argument descriptions. This change ensures that large log files are handled more efficiently by reading them in manageable chunks.
> feat(logfiles): read log files in chunks for efficiency

- cardano_node_tests/tests/reqs_conway.py
- cardano_node_tests/tests/tests_conway/test_committee.py
- src_docs/chang_user_stories_template.rst
- Added internal test case int001 in reqs_conway.py
- Updated test_committee.py to include int001 test case
- Documented internal test case in chang_user_stories_template.rst
> feat(tests): add requirement for DoS fixed in 10.1.4

- src_docs/source/test_results/requirements/chang_user_stories_system_tests.rst
- Updated the latest update date to 2025-01-28
- Added a new section for Internal Test Cases
- Updated various target links for test cases
- Added new test case to prevent potential DoS attack
> feat(docs): update test results and add internal test cases

- cardano_node_tests/tests/reqs_conway.py
- cardano_node_tests/tests/tests_conway/test_drep.py
- src_docs/chang_user_stories_template.rst
- Added internal test case R10_1_3 to reqs_conway.py
- Updated test_drep.py to include new test case
- Updated chang_user_stories_template.rst with new test case details
> feat(tests): add requirement for ledger issue fixed in 10.1.3

- .github/node_upgrade_pytest.sh
- .github/regression.sh
- .github/source_cardano_cli.sh
- .github/source_plutus_apps.sh
- Consolidate PATH management by introducing PATH_APPEND variable
- Update node_upgrade_pytest.sh to use new PATH_APPEND variable
- Modify regression.sh to utilize PATH_APPEND for PATH updates
- Refactor source_cardano_cli.sh to streamline build process and use PATH_APPEND
- Simplify source_plutus_apps.sh to use PATH_APPEND and improve build steps
> refactor(github): simplify PATH management in scripts

- poetry.lock
- pyproject.toml
- Bump cardano-clusterlib from 0.7.2 to 0.7.3 in poetry.lock
- Update cardano-clusterlib dependency in pyproject.toml
> feat: update cardano-clusterlib to version 0.7.3

- README.md
- Corrected grammatical errors and reworded sentences for better clarity.
- Updated instructions for running tests and configuring the environment.
- Enhanced readability and consistency throughout the document.
> fix(docs): improve grammar and clarity in README.md

- cardano_node_tests/cluster_scripts/conway/start-cluster
- cardano_node_tests/cluster_scripts/conway/template-config.json
Resolves https://github.com/IntersectMBO/cardano-node-tests/issues/2927
> feat: use Byron on chain governance for Shelley HF

- cardano_node_tests/tests/test_smash.py
- Changed HTTPStatus import to use the `http` module instead of direct import
- Updated all references to HTTPStatus to use `http.HTTPStatus`
> fix(tests): update HTTPStatus import in test_smash.py

- cardano_node_tests/prepare_cluster_scripts.py
Simplified the assignment of the scripts_dir variable by using a more concise expression. This change improves code readability and maintainability.
> fix(prepare_cluster_scripts): simplify scripts_dir assignment

- cardano_node_tests/utils/dbsync_queries.py
utxo_view was dropped in release 13.6.0.5 of cardano-db-sync
> Update query_utxo for db-sync 13.6.0.5

- cardano_node_tests/testnet_cleanup.py
- cardano_node_tests/testnet_cleanup_info.py
- cardano_node_tests/utils/testnet_cleanup.py
- Simplified logging format in `testnet_cleanup.py` and `testnet_cleanup_info.py`
- Refactored address handling in `testnet_cleanup.py` to use `AddressRecord`
- Added functions to deduplicate and batch transaction inputs
- Improved address cleanup and fund return logic
> refactor: improve logging and address handling

- cardano_node_tests/utils/testnet_cleanup.py
- Change return type of batch_tx_inputs to Generator
- Add comment for deduplication in return_funds_to_faucet
- Update docstring for cleanup_certs
- Add detailed docstring for _get_faucet_payment_rec
> refactor: improve testnet cleanup doc and comments

- cardano_node_tests/utils/testnet_cleanup.py
Updated `get_tx_inputs` to include UTxOs with datum as spendable reference inputs. Improved error logging in `return_funds_to_faucet` to use `LOGGER.exception` for better traceability.
> fix(utils): include UTxOs with datum in tx inputs

- cardano_node_tests/tests/tests_plutus/test_mint_build.py
- cardano_node_tests/tests/tests_plutus/test_spend_build.py
- cardano_node_tests/tests/tests_plutus_v2/test_mint_build.py
Reduced the script funding amounts in test_mint_build.py and test_spend_build.py.
> fix(tests): decrease script funding amounts

- cardano_node_tests/utils/testnet_cleanup.py
Added logging for the cleanup faucet balance in the `cleanup` function of `testnet_cleanup.py`. This provides better visibility into the faucet's balance before and after cleanup operations.
> feat(utils): log cleanup faucet balance in testnet cleanup

- cardano_node_tests/utils/testnet_cleanup.py
Updated the witness count calculation in `testnet_cleanup.py`.
> fix(utils): adjust witness count calculation logic

- cardano_node_tests/utils/testnet_cleanup.py
Enhanced the retry mechanism in `return_funds_to_faucet` to handle `FeeTooSmallUTxO` errors by incrementally increasing witness count. Added multiple retry attempts with detailed logging for better debugging and error handling.
> fix(testnet_cleanup): improve retry logic for fund return

- cardano_node_tests/tests/common.py
Ensure the stake address is registered only when it is not already registered.
> fix(common): register stake address only if unregistered

- .github/node_upgrade_pytest.sh
- Added NETWORK_MAGIC export in step2 and step3 to ensure proper setup.
- Updated binary linking logic in step1 to handle layout changes in archives.
- Added a conditional check to avoid redundant symbolic links creation.
> feat: improve handling of NETWORK_MAGIC and binary setup

- flake.lock
Updated node to 10.3.1 and various dependencies in the flake.lock file.
> feat(flakes): update node to 10.3.1 plus dependencies

- cardano_node_tests/tests/test_node_upgrade.py
Introduce a version comparison to handle UTxO-HD upgrade scenarios. The change ensures that specific log warnings are ignored only when upgrading from pre-UTxO-HD releases.
> feat(tests): add version check for UTxO-HD upgrade handling

- .github/grep_errors.sh
- .github/node_upgrade.sh
- .github/node_upgrade_pytest.sh
- .github/regression.sh
- .github/save_artifacts.sh
- .github/setup_venv.sh
- cardano_node_tests/cluster_scripts/conway/start-cluster
- cardano_node_tests/cluster_scripts/conway_fast/start-cluster
- cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
- cardano_node_tests/cluster_scripts/testnets/start-cluster
- scripts/postgres-start.sh
Enhance robustness of CI and cluster scripts by:
- Using `set -Eeuo pipefail` and error traps for better error reporting.
- Ensuring all scripts consistently initialize and propagate return values.
- Avoiding sourcing scripts with `.` in favor of direct execution.
- Improving artifact handling and error log collection.
- Refactoring cluster start scripts to handle command failures more reliably.
These changes improve diagnostics, make failures more visible, and ensure artifacts and logs are handled consistently across CI workflows.
> fix(ci): improve error handling and reporting in scripts

- .github/cli_coverage.sh
- .github/create_results.sh
- .github/node_upgrade_pytest.sh
- .github/regression.sh
- .github/save_artifacts.sh
Enhance shell scripts to handle cases where artifacts or reports directories are empty or missing. Add checks to print informative error messages and exit with a non-zero status when no files are found. Update script names and calls for consistency. Ensure that optional steps do not fail the pipeline by using `|| :` where appropriate. Also, avoid compressing non-existent scheduling logs.
> fix(ci): improve error handling for missing artifacts/reports

- README.md
Revamp the README for improved clarity and usability:
- Add section headers with emojis for quick navigation.
- Streamline instructions for running tests via GitHub Actions and Nix.
- Add concise tables for environment variables and configuration.
- Simplify local development and cluster management steps.
- Provide clear examples for common workflows.
- Emphasize contributing guidelines and documentation links.
> docs(readme): modernize and clarify usage instructions

- cardano_node_tests/tests/tests_conway/conway_common.py
- cardano_node_tests/tests/tests_conway/test_committee.py
This PR refactors test_committee.py align with the new build Method
> This PR refactors test_committee to align with the new build Method

- cardano_node_tests/tests/tests_conway/test_conway.py
Refactor Conway to use build method
> This PR refactors test_conway.py align with the new build Method
