IntersectMBO/cardano-node-tests

cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_staking.py, cardano_node_tests/utils/clusterlib.py
Make it falsy when no data, so no need to return None instead -
simplifies checking of it's attributes (no need to check for None
first).
=> Simplify StakeAddrInfo

cardano_node_tests/tests/conftest.py
In case we raise failure during processing, env is not saved.
=> Save env before processing artifacts

cardano_node_tests/tests/test_staking.py
and can be run with `-k test_no_reward_unmet_pledge1` without running also
"test_no_reward_unmet_pledge2".
=> Rename test so his name is unique substring

cardano_node_tests/tests/test_update_proposal.py
so waiting for cluster is not counted as test run time
=> Move cluster setup to fixture

cabal_build_tests/fedora/Dockerfile, cabal_build_tests/install-node.sh, cabal_build_tests/readme.md, cabal_build_tests/run-fedora.sh, cabal_build_tests/run-ubuntu.sh, cabal_build_tests/ubuntu/Dockerfile
Two news tests that build Ubuntu/Fedora Docker images and are run following Cabal build instructions in doc/getting-started/install.md. Successful build is verified using cardano-cli.
=> Created cabal_build_tests

Makefile, cardano_node_tests/tests/conftest.py, cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_multisig.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_staking.py, cardano_node_tests/tests/test_transaction_fees.py, cardano_node_tests/tests/test_transactions.py, cardano_node_tests/tests/test_update_proposal.py, cardano_node_tests/utils/cluster_instances.py, cardano_node_tests/utils/clusterlib.py, cardano_node_tests/utils/clusterlib_utils.py, cardano_node_tests/utils/devops_cluster.py, cardano_node_tests/utils/helpers.py, cardano_node_tests/utils/parallel_run.py
Right now we run our test on several pytest workers, but just single cluster instance. This slows things considerably, given we need to "lock" the cluster in case some test modifies global state, like cluster config, pools pledge, etc. (or there's a chance for that, like in case of failure).
Initial measurements showed that with 15 pytest workers and 9 cluster instances the test are able to finish in ~ 1h 15m instead of 6+ hours.
=> Run tests in parallel on multiple cluster instances

cabal_build_tests/readme.md, cardano_node_tests/utils/clusterlib_utils.py, cardano_node_tests/utils/parallel_run.py
When collecting coverage at the end of worker session, there can
potentially be naming collision.
=> Add rand str to timestamped CLI coverage dump

.github/workflows/sync_test.yaml
So it is at least easier to filter them out from git log.
=> Change mail and name for sync tests commits

cabal_build_tests/install-node.sh, cabal_build_tests/readme.md
Considered updated made:
https://github.com/input-output-hk/cardano-node/commit/283a9fe203f3bb84bec763a9cc2c9baf12235564
and
https://github.com/input-output-hk/cardano-node/commit/17d883ef30b4370c5f7dadb6b52ce948e7f90976
=> Update Cabal build tests inline with documentation

setup.cfg
The requirements for sync tests are listed directly in Github Actions.
The cardano-node-tests pip package is not needed for sync tests and thus
there's no need to install sync test requirements as part of cardano-node-tests
package.
=> Remove sync tests requirements from setup.cfg

cardano_node_tests/tests/conftest.py, cardano_node_tests/utils/devops_cluster.py, cardano_node_tests/utils/parallel_run.py
This speeds development a lot, now that we need to wait for hard forks.
=> Add possibility to run tests on already started cluster instance

cardano_node_tests/tests/test_scripts.py, cardano_node_tests/utils/devops_cluster.py, cardano_node_tests/utils/helpers.py
To be able to e.g. skip tests when node version or cardano era doesn't
match.
=> Ability to check and compare node versions and cardano eras

cardano_node_tests/tests/test_native_tokens.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_scripts.py, cardano_node_tests/tests/test_staking.py, cardano_node_tests/tests/test_transaction_fees.py, cardano_node_tests/tests/test_transactions.py, cardano_node_tests/tests/test_update_proposal.py, cardano_node_tests/utils/parallel_run.py
Introduces context manager that handles fixture values caching.
It is used to cache function-scoped fixture, so the value can be reused if another tests run on the same cluster instance.
=> Better fixture caching

sync_tests/sync_test.py
updated the `query tip` parameter names - 1.26.0 and increase the node startup timeout from 30 to 300 secs
=> updated the `query tip` parameter names and the node startup timeout

cardano_node_tests/tests/test_transactions.py
It's needed so we don't try to use the same UTxO from multiple TXs.
=> Revert the waiting for blocks

cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_staking.py
Currently it sometimes fail when the deregistration is submitted close
to epoch boundary. This change makes sure there's enough time to (re)submit
the transaction.
=> Make pool deregistration more robust

cardano_node_tests/tests/conftest.py
Will warn when `cardano-cli` is not running from nix:
```
$ pytest cardano-node-tests/cardano_node_tests/tests/test_transactions.py
WARNING: Not running `cardano-cli` from nix!
================================= test session starts =============
```
Also adds `CARDANO_NODE_SOCKET_PATH` and path to `cardano-cli` to metadata:
```
$ pytest cardano-node-tests/cardano_node_tests/tests/test_transactions.py
================================= test session starts =============
...
metadata: {..., 'cardano-cli exe': '/nix/store/bbfssn60bdq7r33xkgb2l4d9kxxdzn70-cardano-cli-exe-cardano-cli-1.27.0/bin/cardano-cli', 'CARDANO_NODE_SOCKET_PATH': '/home/martink/Source/repos/cardano-node/state-cluster0/bft1.socket'}
...
```
=> Add more metadata and nix check

Makefile, cardano_node_tests/tests/test_staking.py, pytest.ini
For now, enable once stable testing pools are active on given testnet.
=> Exclude tests that require rewards from running on testnets

cardano_node_tests/cluster_scripts/mary/config-bft1.json, cardano_node_tests/cluster_scripts/mary/config-pool1.json, cardano_node_tests/cluster_scripts/mary/config-pool2.json, cardano_node_tests/cluster_scripts/mary/config-pool3.json
```
$ cardano-cli query tip --testnet-magic 42
cardano-cli: QueryEncoderUnsupportedQuery Query GetSystemStart TopLevelQueryDisabled
```
Will be reverted once this issue is fixed.
=> Temporary workaround for `QueryEncoderUnsupportedQuery`

cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_governance.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_staking.py, nix/default.nix, requirements-dev.txt, setup.cfg
Fixes nix build issue
```
Package ‘python3.8-pytest-ordering-unstable-2019-06-19’ in /nix/store/r2ygiv90x2qg2bpxilzabfad1ixnprv6-nixpkgs-unstable-src/pkgs/development/python-modules/pytest-ordering/default.nix:27 is marked as broken, refusing to evaluate.
```
=> Replace pytest-ordering with pytest-order

cardano_node_tests/tests/test_staking.py
Disabled until https://github.com/input-output-hk/cardano-node/issues/3074 is fixed.
=> Withdrawal using `transaction build`

cardano_node_tests/tests/test_smart_contracts.py
Wrong script was used for tests that are supposed to use the "always succeds" script.
Fixtures rename to make the fixture purpose more clear.
=> Fix plutus tests

cardano_node_tests/tests/test_transactions.py
These tests require lot of memory, relieve CI a bit.
=> Skip the `TestManyUTXOs` tests when cluster era != Tx era

cardano_node_tests/tests/test_plutus_spend_build.py, cardano_node_tests/tests/test_plutus_spend_raw.py
2 tests were mistakenly marked with `dbsync` tag.
=> Remove `dbsync` mark from non-dbsync tests

cardano_node_tests/tests/test_metrics.py, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/configuration.py, cardano_node_tests/utils/dbsync_conn.py
This is needed often, so standalone `get_instance_num` added.
=> Simplify getting cluster instance num

nix/default.nix
Error details: 
```
trap 'kill -- $$' INT TERM QUIT; mkdir -p /scratch/cardano-node-tests
./.buildkite/nightly_dbsync.sh
error: anonymous function at /var/lib/buildkite-agent-iohk/builds/packet-ipxe-5-ci5-1/input-output-hk/cardano-node-tests-dbsync/nix/default.nix:1:1 called with unexpected argument 'inNixShell'
at «string»:1:18:
1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (niv) (nix) (gnugrep) (gnumake) (gnutar) (coreutils) (adoptopenjdk-jre-bin) (curl) (git) ]; } ""
|                  ^
… while evaluating anonymous lambda
at «string»:1:1:
1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (niv) (nix) (gnugrep) (gnumake) (gnutar) (coreutils) (adoptopenjdk-jre-bin) …
```
=> Fix issue with nix unexpected argument

cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_ledger_state.py, cardano_node_tests/tests/test_metrics.py, cardano_node_tests/tests/test_protocol.py, cardano_node_tests/utils/versions.py
Some tests are meant to run only with default transaction era. These tests were skipped when transaction era was specified. However in nightly CI jobs the transaction era is always specified, so these tests were always skipped.
This PR changes the logic so that the tests run with default transaction era regardless whether it was specified or not.
=> Fix skips when both cluster and transaction era are specified

cardano_node_tests/tests/test_staking.py
Skip delegation pool check when no "member" type rewards are available.
=> Check only "member" type rewards

.buildkite/nightly_dbsync.sh, cardano_node_tests/cluster_scripts/alonzo/run_dbsync.sh, cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc, cardano_node_tests/cluster_scripts/alonzo_pv5/run_dbsync.sh, cardano_node_tests/cluster_scripts/alonzo_pv5/start-cluster-hfc, cardano_node_tests/cluster_scripts/mary/run_dbsync.sh, cardano_node_tests/cluster_scripts/mary/start-cluster-hfc, cardano_node_tests/cluster_scripts/testnets_nopools/run_dbsync.sh, cardano_node_tests/cluster_scripts/testnets_nopools/start-cluster
cardano-db-sync and cardano-db-sync-extended were merged.
Target db-sync-extended does not exists on master anymore.
Details here:
https://github.com/input-output-hk/cardano-db-sync/pull/904
=> Update scripts to use db-sync instead of db-sync-extended

cardano_node_tests/utils/configuration.py
Missing changes during db-sync scripts update for config file caused CI
error:
```
E   FileNotFoundError: [Errno 2] No such file or directory: '/scratch/workdir/cardano-db-sync/db-sync-node-extended/bin/cardano-db-sync-extended'
```
=> Fix CI error about missing db-sync-extended

cardano_node_tests/tests/test_staking.py
The test needs to obtain exclusive access to the pots so it doesn't affect other tests.
=> Make sure no other test can use treasury and reserves pots

cardano_node_tests/tests/conftest.py, cardano_node_tests/tests/test_metrics.py
This way tests will be skipped only when they were selected to run, not everytime the test file is imported.
=> Better metrics skip

cardano_node_tests/tests/delegation.py
This pool is never locked for exclusive access by destructive tests.
=> Use pool3 for delegation

cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_delegation.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_staking.py, cardano_node_tests/tests/test_update_proposals.py
The full testrun execution should now be quicker. Highest priority is
now 5 (instead of former 1), so we have buffer for even more priority tests in
the future without the need to re-number everything.
=> Reorder tests

cardano_node_tests/tests/test_dbsync.py
It can result in failures like
```
>           if rec.slot_no < prev_rec.slot_no:
E           TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
=> Fix failure when some of the items of tuple is None

cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_ledger_state.py
Add more checks to the existing tests - compare stake addresses, delegations and amounts with ledger state.
Also merge with `test_ledger_state_keys` as getting ledger state is expensive.
XFAIL for now, until all corner cases are handled.
=> Compare `stake-snapshot` output with ledger state

cardano_node_tests/tests/test_ledger_state.py
instead of from `query stake-pools`, so we get even those pools that are
not running.
=> Get pool ids from delegations

cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_plutus_mint_raw.py, cardano_node_tests/tests/test_plutus_spend_raw.py, nix/cardano-clusterlib.nix, setup.cfg
Check that pretty printed `query utxo` output looks as expected.
Closes https://github.com/input-output-hk/cardano-node-tests/issues/563
=> Add `test_pretty_utxo`

cardano_node_tests/utils/cluster_management.py
Resulting dir name was confusing, e.g 'addrs_data_ci31'. Now it is 'addrs_data_ci3_1', meaning: addresses data for cluster instance 3 with pytest temp dir index 1.
=> Add separator to "addrs_data" temp dir name

Makefile, cardano_node_tests/utils/artifacts.py, cardano_node_tests/utils/cluster_management.py, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/helpers.py
We now run db-sync tests with `DbSyncAbortOnPanic=1`. That means db-sync service fails on serious errors and keeps failing after restart. While it is desirable to not test on db-sync that is no longer in reliable state, it affects all remaining tests as there's no longer a working db-sync service.
This PR adds checks that all cluster instance services are healthy. If that's not the case, a fresh cluster instance is started.
=> Restart cluster instance when any service fails

cardano_node_tests/cluster_scripts/alonzo/start-cluster-hfc, cardano_node_tests/cluster_scripts/alonzo/supervisor.conf, cardano_node_tests/cluster_scripts/alonzo_p2p/start-cluster-hfc, cardano_node_tests/cluster_scripts/alonzo_p2p/supervisor.conf, cardano_node_tests/cluster_scripts/testnets/supervisor.conf, cardano_node_tests/cluster_scripts/testnets_nopools/supervisor.conf
Don't automatically restart db-sync on local network. Db-sync is expected to exit on important errors and there's no point in restarting it.
Increase time after which a service is considered to be started from 1s to 3s.
=> Change supervisor.conf

cardano_node_tests/cardano_cli_coverage.py, cardano_node_tests/utils/cluster_management.py, cardano_node_tests/utils/types.py
Use asserts to ensure `Iterable[str]` means sequence of strings.
=> Use generic `Iterable` type

Makefile, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/dbsync_queries.py, cardano_node_tests/utils/model_ekg.py
Add option to run pytype during `make lint` when available.
Fix / warkaround issues found by pytype.
=> Optional checks using pytype

cardano_node_tests/tests/test_plutus_delegation.py
Skip the test when `transaction buid` cannot be used or Tx era < Alonzo.
=> Skips for plutus delegate test

nix/cardano-clusterlib.nix, setup.cfg
Update clusterlib to 0.2.1.
Fix issue that protocol parameters were passed to build-raw command at wrong times when using Mary-era transactions.
=> Fix usage of pparams in Mary era Tx

cardano_node_tests/tests/kes.py, cardano_node_tests/tests/test_kes.py
Change `test_expired_kes` so that blocks are still being minted and so the `query kes-period-info` command can be used in the test.
=> Merge `test_expired_kes` and `test_op_cert_with_expired_kes`

cardano_node_tests/utils/logfiles.py
This error can happen when p2p is on.
=> Ignore error in log file when node is shutting down

cardano_node_tests/tests/test_transactions.py
Explicitly use all the methods that are needed for preparing and submitting a Tx (instead of using the `send_funds` wrapper) so the test function can be used for debugging Tx submission issues.
=> Make the simplest Tx test more explicit

cardano_node_tests/tests/test_blocks.py, cardano_node_tests/tests/test_delegation.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_ledger_state.py, cardano_node_tests/tests/test_plutus_delegation.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_staking.py, cardano_node_tests/utils/clusterlib_utils.py
Don't check if slot number after waiting matches the specified interval (i.e. no need to wait for new tip by default).
The interval doesn't need to be in current epoch by default.
=> Change defauts for `wait_for_epoch_interval`

cardano_node_tests/tests/test_native_tokens.py
=> Fix `ValueNotConservedUTxO` when input UTxO already has tokens

cardano_node_tests/tests/test_plutus_delegation.py, cardano_node_tests/tests/test_plutus_mint_build.py, cardano_node_tests/tests/test_plutus_mint_raw.py, cardano_node_tests/tests/test_plutus_spend_build.py, cardano_node_tests/tests/test_plutus_spend_raw.py
It was necessary to allow just single test per Plutus script running at a time. Remove this limitation.
=> Remove the need to lock Plutus spending tests

cardano_node_tests/tests/common.py, cardano_node_tests/tests/conftest.py, cardano_node_tests/tests/test_delegation.py, cardano_node_tests/tests/test_plutus_delegation.py, cardano_node_tests/tests/test_plutus_mint_build.py, cardano_node_tests/tests/test_plutus_mint_raw.py, cardano_node_tests/tests/test_plutus_spend_build.py, cardano_node_tests/tests/test_plutus_spend_raw.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_transactions.py
Uses `PYTEST_CURRENT_TEST` env variable instead of expensive `inspect`.
=> More efficient way to get test ID

cardano_node_tests/tests/test_plutus_spend_build.py
In Python the `**` is exponentiation operator, the `^` is bitwise XOR.
`2 ^ 64 == 66` and `2 ** 64 == 18446744073709551616` (that's the number we want)
=> Fix value ranges

cardano_node_tests/tests/plutus_common.py, cardano_node_tests/tests/test_plutus_spend_raw.py
Split negative and valid scenarios into separate tests.
=> Test both typed and untyped redeemers and datum

cardano_node_tests/tests/test_staking_no_rewards.py, cardano_node_tests/tests/test_staking_rewards.py
Several tests use pool owner payment address for Tx fees. Make sure that pledge is still met at the end of such tests.
=> Make sure pledge is met

cardano_node_tests/tests/test_transactions.py
Even though it should not be possible to submit the Tx, in reality the Tx is going through. Therefore we need to wait for two new blocks after submitting the Tx so we are sure that the input UTxO is really spent. Otherwise some other test may attempt to use the same UTxO and fail because of `BadInputsUTxO`.
=> Wait for 2 new blocks on submit

cardano_node_tests/tests/test_transactions.py
e.g. when testing older release of node
=> Skip test_wrong_tx_era when last know era is not available

cardano_node_tests/tests/test_staking_rewards.py
It can rarely happen that the tip is not updated for longer than 35s. The `wait_for_new_epoch` depends on info from current tip. When `wait_for_new_epoch` gets the information that we are in next epoch, we can already be past the 35s.
=> Wait up to 50s in new epoch

nix/cardano-clusterlib.nix, setup.cfg
Change introduced in https://github.com/input-output-hk/cardano-node/pull/4170/commits/f0475c99ca6dcc495884d4e159f2516fecdcd939. The data is now nested.
=> Update clusterlib to 0.3.0rc11 to fix getting pool-params on node 1.35.1+

cardano_node_tests/utils/dbsync_utils.py, cardano_node_tests/utils/tx_view.py
=> Script withdrawals are no longer listed among normal withdrawals

cardano_node_tests/tests/test_plutus_v2_spend_build.py, cardano_node_tests/tests/test_plutus_v2_spend_raw.py
This was broken by https://github.com/input-output-hk/cardano-node-tests/pull/1317
=> Add `dst_addr`s that were removed by mistake

doc/running_local_cluster.md
In order to avoid some possible incompatibility in some of the python package(s) provided by `nix-shell` and some of the python package(s) provided by your virtual environment it might be needed to use export:
`export PYTHONPATH="$(echo $VIRTUAL_ENV/lib/python3*/site-packages)":$PYTHONPATH`
before running tests on local cluster.
=> Improve docs for running tests on local cluster

cardano_node_tests/utils/cluster_management.py, cardano_node_tests/utils/configuration.py
Ensure that the framework doesn't delete cluster state that was not created by the framework.
Also check that `CARDANO_NODE_SOCKET_PATH` value is valid for use by testing framework before starting test session.
=> Protect state cluster dir that was not created by framework

doc/mir_cert_test_example_manual_steps.md, doc/running_local_cluster.md, doc/smash/smash_faq.md, doc/smash/smash_tests_and_debugging_examples.md, doc/stake_credential_history_tool.md
Several SQL responses were shown as text, but they did not format into tables. To show them as tables, I took them out of the scope of the ``` SQL block. The result is not the way they would be rendered in a terminal window, but IMO it is more readable than the way they were.
=> CTD-54 changes to conform to IOG style guide

cardano_node_tests/tests/test_cli.py
and remove "whole UTxO" query test that is now too expensive on any testnet.
=> Don't run tests that don't interract with blockchain on testnets

cardano_node_tests/tests/test_tx_many_utxos.py
Make sure "many utxos" tests are scheduled in initial batch (`order(5)`), all run on the same pytest worker, so the expensive setup needs to happen just once (`xdist_group(name="many_utxos")`) and all run on the same cluster instance (same reason as above - `mark="many_utxos"`).
=> Group "many utxos" tests

Makefile, cardano_node_tests/pytest_plugins/xdist_scheduler.py, cardano_node_tests/tests/conftest.py
Schedule long running tests optimally:
* only single long-running test per pytest worker
* long runnig tests are schduled as early as possible
=> Add custom scheduler for pytest-xdist plugin

.buildkite/db_sync_full_sync.yml, .buildkite/db_sync_snapshot_restoration.yml
Update Buildkite queue from `benchmark_large` (obsolete and gone) to just `benchmark`
=> Update Buildkite agent queue

cardano_node_tests/cluster_scripts/babbage/start-cluster-hfc, cardano_node_tests/cluster_scripts/babbage_fast/start-cluster-hfc
The ticker can be max up to 5 characters long.
=> Short pools ticker so there is more space for pool number

.github/workflows/nightly_upgrade.yaml
Currently the results are not picked up by reports aggregator due to naming mismatch.
=> Rename to follow nightly tests naming convention

cardano_node_tests/tests/common.py, cardano_node_tests/tests/test_native_tokens.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/test_scripts.py, cardano_node_tests/tests/test_staking_rewards.py, cardano_node_tests/tests/test_tx_fees.py, cardano_node_tests/tests/test_tx_negative.py, cardano_node_tests/tests/test_tx_unbalanced.py, cardano_node_tests/tests/tests_plutus/test_mint_negative_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_datum_build.py, cardano_node_tests/tests/tests_plutus/test_spend_datum_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_datum_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_datum_raw.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_secp256k1_build.py
Hypothesis tests cannot use `rand` module, so the unique string is based on current timestamp.
=> Make sure to use uniqe `temp_template` for each test iteration

cardano_node_tests/tests/test_mir_certs.py
Make sure the available amount is always exceeded, even on fact cluster where the test can run in first epoch.
=> Increase amount to transfer

cardano_node_tests/tests/test_mir_certs.py
If local cluster is started in latest era instead of going from Byron, there might be insufficient funds in pots.
=> Skip all tests in `TestMIRCerts` when HF shortcut is used

cardano_node_tests/utils/logfiles.py
There can be an error message in log file that can be safely ignored if there's a certain expected message that comes prior to the error message.
E.g. the `TraceNoLedgerState` error message can be ignored if there is a `Switched to a fork, new tip:  ...` message that comes (almost) immediately before the error message.
This PR adds ability to look back for expected messages.
=> Add possibility to look back in log file for expected messages

check_env.sh
The `psql` command is needed when setting up db-sync.
=> Check that `psql` command is available

cardano_node_tests/tests/test_tx_negative.py
* use `build` command only when `use_build_cmd == True`
* skip on Shelley-era Tx
=> Fix failing negative lower bound tests

.github/node_upgrade.sh, .github/regression.sh, flake.nix
We no longer use pure shell, so there's no need to install nix. Moreover it istalls old nix (2.7.x) that doesn't work with latest cardano-node.
=> Use system nix in `base`

cardano_node_tests/cluster_management/manager.py, cardano_node_tests/tests/conftest.py, cardano_node_tests/utils/logfiles.py
Hide excessive traceback; raise more descriptive exception.
=> Make reporting of log errors more readable

cardano_node_tests/tests/test_ledger_state.py
rather than total active stake
=> The `stake-snapshot` command now reports total stake

cardano_node_tests/tests/test_scripts.py
The wording of the error is diffeent for node <= 1.35.6
=> Make legacy error string compatible with current tests

cardano_node_tests/utils/cluster_scripts.py
See
* <https://github.com/input-output-hk/cardano-node/issues/4559>
* <https://github.com/input-output-hk/cardano-node/pull/4563>
=> Add support for the new P2P topology format

cardano_node_tests/tests/test_scripts.py
The error message will change again after the merge of cardano-node PR 3478/4956:
`The script language SimpleScriptLanguage SimpleScriptV2 is not supported in the Shelley era.`
=> update error message when use script v2 + shelley tx

cardano_node_tests/split_topology.py, cardano_node_tests/tests/test_rollback.py, cardano_node_tests/utils/cluster_scripts.py, nix/cardano-clusterlib.nix, scripts/test_rollbacks.sh, setup.cfg
The PR adds support for splitting local cluster into two clusters that don't communicate with each other, and support for restoring the original cluster. This enables testing of rollbacks.
There are following scenarios tested in this PR:
1. global consensus is reached after rollback, in situation where less than `securityParam` blocks were produced since cluster split
2. global consensus is not reached when more than `securityParam` blocks were produced, and the result is permanent fork
=> Add rollback testing

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/utils/configuration.py
The dev cluster no longer needs to be the "cluster0". This enables running multiple instances of local dev cluster at the same time.
=> Allow use of any instance number for local dev cluster

cardano_node_tests/tests/kes.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_staking_no_rewards.py
KES expiration date is reported in UTC, however the expected expiration date is not calculated in UTC. Depending on time of the day when the test is ran and system timezone, the test can fail with errors like:
```
E               AssertionError: Failed checks on `kes-period-info` command:
E               The kes expiration date in check '1': 2023-05-27 vs 2023-05-28
E               The kes expiration date in check '2': 2023-05-27 vs 2023-05-28
E               The kes expiration date in check '3': 2023-05-27 vs 2023-05-28
E               The kes expiration date in check '4': 2023-05-27 vs 2023-05-28.
```
=> Fix: expect KES expiration date in UTC tz

.github/regression.sh, cardano_node_tests/tests/conftest.py
When running tests using the `regression.sh` script, binaries can be overridden by placing them into a `.bin` directory in the root of the repo.
=> Add ability to override node and cli binaries

cardano_node_tests/tests/test_env_network_id.py
The affected tests are very quick, and it can happen that the test is finished and log error ignore rule is delete before the actual error message gets written to a log file. As a result, it can happen that the error is not ignored and it is reported by the next test.
=> Wait for log messages to get written to log files

cardano_node_tests/utils/logfiles.py
We sometimes see this error on CI. It seems time is not synced properly on GitHub runners.
=> Ignore `TraceBlockFromFuture` on CI

cardano_node_tests/tests/test_cli.py
The test can hang indefinitely. Disable until timeout is implemented.
=> Temporarily disable mainnet ping test

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/resources_management.py, cardano_node_tests/tests/conftest.py, cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_xdist_helper.py, cardano_node_tests/utils/cluster_nodes.py
and doesn't mask other unrelated arguments.
=> Make sure `noqa` is always applied on single argument

cardano_node_tests/utils/blockers.py
One thing I forgot to change in the original PR 1816. Expensive operations should not be performed in property. Here happens the `self.gh_issue.is_closed()` that performs expensive API call to GitHub.
=> Fix property vs method

.github/source_dbsync.sh, doc/running_local_cluster.md
`cardano-db-sync` regression tests are failing with:
```
++ git rev-parse HEAD
++ nix-build -A cardano-db-sync -o db-sync-node
error: getting status of '/home/runner/work/cardano-node-tests/cardano-node-tests/run_workdir/cardano-db-sync/default.nix': No such file or directory
```
Link: https://github.com/input-output-hk/cardano-node-tests/actions/runs/5012973825/jobs/8985531621
Update `nix` build command structure to build new version of `cardano-db-sync` 
from:
`nix-build -A cardano-db-sync -o db-sync-node`
to:
`nix build .#cardano-db-sync -o db-sync-node`
=> Update nix build command for db-sync 13.1.1.0

poetry.lock, pyproject.toml
There is a vulnerability in the requests version we use. See https://github.com/input-output-hk/cardano-node-tests/security/dependabot/2
=> Update requests to 2.31.0

cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_env_network_id.py, cardano_node_tests/tests/test_tx_negative.py, cardano_node_tests/tests/tests_plutus/test_spend_raw.py
When ignore rule is added after a command that produces the error has already run, another test can finish right after the error message is added to log file and before the ignore rule is created, and report the error. Fix this race condition - the ignore rule has to be added before the error-producing command runs.
=> Fix race conditions in tests that use `add_ignore_rule`

.github/workflows/regression_reusable.yaml, .github/workflows/upgrade_reusable.yaml, cardano_node_tests/utils/blockers.py, deploy_doc.sh, src_docs/source/conf.py
We still need to use `GH_TOKEN` secret inside reusable workflows due to `GITHUB_TOKEN` being reserved name.
=> Rename `GH_TOKEN` to more standard `GITHUB_TOKEN`

cardano_node_tests/tests/test_env_network_id.py
The fixture could run long before test is started (test is waiting for `cluster` fixture) and so the ignore rule can expire even before the test is started.
=> Ignore log errors using method instead of fixture

.github/regression.sh, .github/source_dbsync.sh, .github/source_plutus_apps.sh, cardano_node_tests/tests/plutus_common.py, cardano_node_tests/tests/tests_plutus/test_mint_build.py, cardano_node_tests/tests/tests_plutus/test_mint_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_build.py, cardano_node_tests/tests/tests_plutus/test_spend_raw.py, cardano_node_tests/utils/clusterlib_utils.py
Make `create-script-context` tool availoable when running on CI and run tests that depend on the tool by default (can be disabled by exporting `CI_ENABLE_PLUTUS_APPS=false`).
=> Enable `create-script-context` in CI

cardano_node_tests/utils/dbsync_check_tx.py, cardano_node_tests/utils/dbsync_queries.py, cardano_node_tests/utils/dbsync_types.py, cardano_node_tests/utils/dbsync_utils.py
Now checks reference scripts in all txins where reference scripts are allowed.
Also changes SQL sub-queries into joins.
Tested (with db-sync on):
```
=== 399 passed, 20 skipped, 4 xfailed, 4 warnings in 2858.17s (0:47:38) ===
```
=> Fix reference scripts checks in db-sync

.github/workflows/node_mainnet_tx_count_per_epoch.yaml
Update GH Actions to new version:
>Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
This is automatic (scheduled) workflow so I think it needs to be updated on `master`:
```
on:
schedule:
- cron: '0 8 * * *'
```
=> Update GH Actions for tracking mainnet TX per epoch

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/tests/conftest.py, cardano_node_tests/utils/helpers.py, cardano_node_tests/utils/logfiles.py
Add new `framework.log` log file for framework-related messages. The new log file exists per pytest worker and is checked during each test teardown, same as node log files. It is currently used for logging failures to start cluster instances.
The rationale behind the new log file is that tests can now report framework issues that would otherwise be silently ignored. Eg. when cluster instance fails to start, like it was the case because of node issue https://github.com/input-output-hk/cardano-node/issues/5294, the failure would not be reported and tests would continue running on working cluster instances.
=> Add the `framework.log` log file for framework-related messages

cardano_node_tests/utils/cluster_scripts.py
Don't rely on resolving using /etc/hosts as this can be configured differently on every system (eg. in separate network namespaces).
=> Use either IP address or DNS name

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/manager.py, cardano_node_tests/tests/conftest.py, cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_pools.py, cardano_node_tests/utils/logfiles.py, cardano_node_tests/utils/temptools.py
Initialize pytest temp dirs with value of `tmp_path_factory` in `conftest.py`, so the value of `tmp_path_factory` is needed only once during initialization.
=> Initialize pytest temp dirs once

cardano_node_tests/utils/versions.py
There's no reliable way to check if a node version is development version or release. As a workaround, we need to check both version and revision.
=> Record revision of last node release

cardano_node_tests/tests/test_cli.py
The issue is fixed in cardano-cli that is not used in cardano-node yet.
=> Don't check node issue 5245 on development node versions

cardano_node_tests/utils/blockers.py
That can be useful when the issue was fixed in a project, but the fixed version was not integrated into node master yet.
=> Add `check_on_devel` to generic blocker

cardano_node_tests/tests/test_tx_basic.py, cardano_node_tests/tests/test_tx_unbalanced.py, cardano_node_tests/tests/tx_common.py
Looks like https://github.com/input-output-hk/cardano-node/issues/4061 was fixed.
=> Use fixed min UTxO value

.github/nix_override_cardano_node.sh
See https://github.com/nix-community/poetry2nix/issues/1366 and https://github.com/nix-community/poetry2nix/pull/1368
=> Lock poetry2nix to a working version until issue 1366 is fixed

cardano_node_tests/cluster_scripts/conway_fast/start-cluster
There is only one version of Alonzo genesis possible for Conway era as we are concerned only with testing latest node master.
=> Remove code for using multiple Alonzo genesis files

flake.nix
As we --override-input cardano-node, we may end up with different nixpkgs version and need to be able to use multiple.
=> Make p2n version conditional on the nixpkgs version we use.

cardano_node_tests/cluster_scripts/conway/run-cardano-submit-api, cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/run-cardano-submit-api
If node can run in Conway, submit-api is recent enough to have `--metrics-port`.
=> Assume `--metrics-port` is always available

cardano_node_tests/tests/test_tx_basic.py, cardano_node_tests/tests/test_tx_negative.py
The `--ttl` is no longer needed even for shelley Txs.
=> Fix test for building Shelley Tx with no ttl

cardano_node_tests/tests/tests_conway/test_voting.py
There were only single action created instead of 3 when they share the same anchor.
=> Fix number of withdrawal actions

cardano_node_tests/tests/test_mir_certs.py
MIR certitficates will be deprecated in Conway era.
=> Update test_mir_certs.py to run only in eras before Conway

cardano_node_tests/tests/tests_conway/test_drep.py, cardano_node_tests/utils/dbsync_queries.py, cardano_node_tests/utils/dbsync_types.py, cardano_node_tests/utils/dbsync_utils.py
For `Dreps`  there is only one table `drep_registration` that contains both:
- registrations 
- deregistrations
```sql
select dr.id, dr.tx_id, dr.cert_index, dr.deposit, dr.drep_hash_id, dr.voting_anchor_id, dh.raw, dh.view, dh.has_script from drep_registration as dr inner join drep_hash  dh on dh.id = dr.drep_hash_id where dh.raw = '\x27497d7db01ce343862ad3d58c6f6eb8b9321d830be394c0f295fd1c'
id | tx_id | cert_index | deposit  | drep_hash_id | voting_anchor_id |                            raw                             |                           view                           | has_script 
----+-------+------------+----------+--------------+------------------+------------------------------------------------------------+----------------------------------------------------------+---------- …
```
=> Add drep de/registration db-sync checks

cardano_node_tests/tests/tests_conway/conftest.py, cardano_node_tests/tests/tests_conway/test_committee.py
Otherwise it can be e.g. emptied by other tests mid test.
=> Mark committee as in use

cardano_node_tests/tests/test_cli.py
The check was failing when value corresponding to "slotInEpoch" was 0.
=> Check key presence, not the value

cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_conway/test_constitution.py, src_docs/requirements_mapping.json
CIP073
> As a Stakeholder I want the ledger to adjust the local state query protocol to accommodate for new queries that provide insights about governance, at least:
> 
> - Governance actions currently staged for enactment (1)
> - Governance actions under ratification, with the total and percentage of yes stake, no stake and abstain stake (2)
> - The current constitutional committee (3), and constitution hash digest (4)
This is partial covered, it's missing point (2) that we have to confirm the proper behaviour
=> Update Conway CIP073 coverage

cardano_node_tests/utils/dbsync_utils.py
Update expected fetch error string. 
Local tests passed:
```
pytest -k "test_stake_pool_not_avail_metadata" cardano_node_tests
==================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /nix/store/lx8vhp4fxclp494svlfis3sb2g8z4l9h-python3-3.10.12/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/artur/Downloads/NewTests/cardano-node-tests/.hypothesis/examples')
metadata: {'Python': '3.10.12', 'Platform': …
```
=> Fix metadata test

cardano_node_tests/tests/test_dbsync.py, cardano_node_tests/utils/dbsync_queries.py, cardano_node_tests/utils/dbsync_utils.py
Update to fix issues introduced by db-sync sancho-4-2-0 changes.
Full test log:
[testrun-full.txt](https://github.com/IntersectMBO/cardano-node-tests/files/15065862/testrun-full.txt)
HTML report:
[testrun-report.tar.gz](https://github.com/IntersectMBO/cardano-node-tests/files/15065899/testrun-report.tar.gz)
Before changes results looked like this:
```
SKIPPED [2] cardano_node_tests/tests/tests_plutus/test_delegation.py:687: PlutusV1 doesn't support reference scripts
SKIPPED [1] cardano_node_tests/tests/test_cli.py:965: The 'total_stake' scenario not available with this cardano-cli version.
< ... >
XFAIL cardano_node_tests/tests/tests_plutus/test_spend_raw.py::TestLocking::test_context_equivalence - reason: <GHIssue: IntersectMBO/plutus-apps#1107>: PlutusScriptV1 custom redeemer.
FAILED …
```
=> Update to fix issues introduced by db-sync sancho-4-2-0 changes

README.md
The env variables need to be already set before running `prepare-cluster-scripts`.
=> Swap order of steps needed for dev cluster

cardano_node_tests/tests/common.py
The PlutusV3 scripts need to be rewritten because of CIP-69.
=> Temporarily disable PlutusV3 tests on 8.12.0+

cardano_node_tests/cluster_scripts/conway/dbsync-config.yaml, cardano_node_tests/cluster_scripts/conway_fast/dbsync-config.yaml
- EnableFutureGenesis flag - when false or missing, the conway genesis file is ignored
=> Add `EnableFutureGenesis` flag to db-sync config

cardano_node_tests/tests/reqs_conway.py, cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_conway/test_drep.py, cardano_node_tests/tests/tests_conway/test_info.py, cardano_node_tests/tests/tests_conway/test_pparam_update.py
The Conway tests which are not already covered on existing test topics are:
- DRep Id is blake2b_224 of DRep Vkey
- Delegation change
- No multiple Vote delegation
- Vote Delegation without stake registration
- DRep no multiple registrations
- DRep no retirement before register
- Deposit return for committee
- Info deposit return after expiry
- Update Protocol Params action's deposit return after expiry and enactment
=> Addition of Conway Tests related to delegation changes, drep multiple registration, deposit returns.

cardano_node_tests/tests/tests_conway/test_pparam_update.py
Some `check_conway_gov_action_proposal_description` calls were made with update proposals that were not in scope, and the test failed with `UnboundLocalError`.
=> Fix unbound variables; call check function with kwargs

.github/workflows/db_sync_docker_sync_test.yaml
The old way of passing flags will not work with new configuration changes for cardano-db-sync.
As long as there is no new way for passing custom config files to docker compose - remove old tests for flags that will be broken.
=> Update docker tests

cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/utils/dbsync_utils.py
data returned by query committee-state:
```
{
"committee": {
"keyHash-0daa16ed59809a111ae2b7189f69631422562fabf5aa1a6f6f4a0e58": {
"expiration": 10000,
"hotCredsAuthStatus": {
"contents": {
"keyHash": "2a7a8a3038137d749bce268961a7375417dfdf856a4388e2ba7b4e38"
},
"tag": "MemberAuthorized"
},
"nextEpochChange": {
"tag": "NoChangeExpected"
},
"status": "Active"
},
...
"epoch": 52,
"threshold": 0.6
}
```
=> fix_test_add_rm_committee_members

cardano_node_tests/tests/conftest.py, cardano_node_tests/utils/dbsync_queries.py
We have db-sync nightly job failures that there is not enough space left on the github runners:
> Unhandled exception. System.IO.IOException: No space left on device
=> Respin local testnet when db-sync db is too large

cardano_node_tests/utils/dbsync_queries.py, cardano_node_tests/utils/dbsync_utils.py
The `committee_member` table lists both existing members and proposed members for each `committee_id`. Therefore to get only the proposed members, we need to filter out the existing members.
Also adding more infor to the existing asserts to help with debugging.
=> Get proposed committee members by filtering out the existing members

cardano_node_tests/tests/tests_plutus_v2/test_mint_secp256k1_raw.py
Previously there was a '(' in the expected error message, which was now removed.
=> Fix expected error messages in secp256k1 minting tests

cardano_node_tests/utils/dbsync_utils.py
More robust check where we don't need to care about total number of CC members.
=> Check that new CC members are present in the DB

cardano_node_tests/tests/tests_conway/test_treasury_donation.py
Now that all tests mark their usage of the "reward" pot, we can make the assumption that no other tests are chaging the pot and we can make more detailed checks.
=> Make the treasury update check more detailed

flake.nix
- Add `curl` to be included in the list of nativeBuildInputs.
- Ensured consistent ordering for better readability and maintenance.
=> Add curl to flake.nix

cardano_node_tests/tests/tests_conway/test_drep.py
Instead of `payment_addr`, use the `payment_addr_rewards` fixture in the `custom_drep_rewards` fixture to use the correct cluster instance.
=> fix(test_drep): use payment_addr_rewards

.github/regression.sh, .github/workflows/regression.yaml, cardano_node_tests/tests/test_tx_basic.py, cardano_node_tests/utils/configuration.py, cardano_node_tests/utils/versions.py
This commit updates the default cluster era from "babbage" to "conway" across various scripts and configuration files. The changes include modifying the default values in regression scripts, workflow files, test cases, and configuration utilities to reflect the new default cluster era.
=> feat: update default cluster era to conway

.github/regression.sh
Updated the regression script to handle the conway era correctly. Now, if either TX_ERA or CLUSTER_ERA is set to "conway", TX_ERA will be unset and COMMAND_ERA will be set to "conway". This ensures proper handling of the conway era in the script.
=> fix: handle conway era in regression script

.pre-commit-config.yaml, cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/tests/conftest.py, cardano_node_tests/tests/tests_conway/test_guardrails.py
Updated the ruff-pre-commit hook from version v0.5.5 to v0.6.3 in the .pre-commit-config.yaml file. This ensures we are using the latest features and fixes provided by the ruff-pre-commit tool.
=> Update ruff-pre-commit to v0.6.3

.github/regression.sh
- Introduced _cleanup function to stop all running cluster instances and PostgreSQL.
- Added a trap to call _cleanup on SIGINT (Ctrl+C).
- Replaced direct calls to stop_instances and stop_postgres with _cleanup function.
=> feat: add cleanup function and trap for SIGINT

cardano_node_tests/tests/tests_conway/test_drep.py
Removed the redundant start call for `reqc.cli011` in the test_drep.py file. The URL is now retrieved once and used for both reqc.cli011 and reqc.cip023.
=> refactor(tests): remove redundant requirement start call

cardano_node_tests/tests/test_pools.py
Updated the `_check_staking` function to wait for new blocks instead of epochs when checking if a stake pool is registered. This change ensures faster feedback.
=> fix(tests): update staking check to use new block wait

cardano_node_tests/tests/test_dbsync.py
Extended the sleep duration from 120 to 300 seconds to ensure db-sync has ample time to catch up.
=> fix(tests): increase sleep time for db-sync reconnect

cardano_node_tests/tests/issues.py, cardano_node_tests/tests/test_cli.py
- Updated cardano-cli issue 49
- Added handling for new error message in test_cli.py for cardano-cli version 9.4.1.1+
=> fix(tests): update cardano-cli issue 49 and handle new error message

cardano_node_tests/tests/tests_conway/test_update_plutusv2_builtins.py
Add a wait interval to ensure there is enough time to submit the votes within one epoch. This change helps in avoiding timing issues during the voting process.
=> feat(tests): ensure enough time for vote submission

cardano_node_tests/cluster_management/cluster_getter.py
Moved the cluster respin check to occur after the marked tests are processed. If marked tests need to respin the cluster, we need to check if respin is needed *after* we processed the marked tests.
=> fix(cluster): move respin check after marked tests

.github/cli_coverage.sh, Makefile, cardano_node_tests/cluster_scripts/babbage/start-cluster, cardano_node_tests/cluster_scripts/babbage_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster, cardano_node_tests/cluster_scripts/testnets/start-cluster, poetry_update_deps.sh, setup_dev_venv.sh
Replaced all instances of `type` with `command -v` for checking command existence in various scripts. This change improves compatibility and consistency across different shell environments.
=> refactor: replace `type` with `command -v` for checks

cardano_node_tests/tests/test_rollback.py, cardano_node_tests/tests/tests_conway/test_committee.py
Corrected a typo in a comment in `test_rollback.py` and adjusted the position of the `@pytest.mark.dbsync` decorator in `test_committee.py` for better readability.
=> fix(tests): correct comments and decorators in tests

cardano_node_tests/cluster_scripts/conway/start-cluster
The path for the genesis.json file was incorrect in the start-cluster script. This change updates the path, ensuring the script reads the correct genesis.json file.
=> fix(start-cluster): correct genesis.json file path

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_reconnect.py, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/configuration.py
Node now delays initial request for transactions from a client to conserve network resources in case he disconnects relatively quickly for reasons in the referenced issue.
- Introduced TX_SUBMISSION_DELAY variable
- Updated start-cluster scripts to use TX_SUBMISSION_DELAY instead of hardcoded sleep values.
- Modified test_kes.py and test_reconnect.py to pass delay parameter when restarting nodes.
- Updated cluster_nodes.py to accept delay parameter for node restart functions.
- Added TX_SUBMISSION_DELAY to configuration.py with a default value of 60 seconds.
=> feat: add TX_SUBMISSION_DELAY to cluster scripts

cardano_node_tests/tests/tests_plutus/test_spend_raw.py
Updated test_spend_raw.py to handle multiple expected errors by using a tuple instead of a single string. This change ensures compatibility with different versions of cardano-node and improves error handling in tests.
=> refactor(tests): handle multiple expected errors

cardano_node_tests/tests/test_tx_fees.py
The assertion message for the fee option has been updated to check for a more general error message so it matches both old and new error messages.
=> fix(tests): update fee assertion in test_tx_fees.py

cardano_node_tests/tests/issues.py, cardano_node_tests/tests/test_tx_unbalanced.py
Updated test assertions to handle the new "Illegal Value in TxOut" error message introduced in cardano-node version 9.2.0. This ensures that the tests remain compatible with the latest node version.
- Added "Illegal Value in TxOut" to relevant assertions.
- Maintained compatibility with previous error messages.
=> fix(tests): handle new error message in node 9.2.0+

cardano_node_tests/tests/test_native_tokens.py
Updated the error assertion in `TestTransfer` to include the new error message "Illegal Value in TxOut" introduced in node version 9.2.0+. This ensures compatibility with the latest node version while maintaining backward compatibility with previous error messages.
=> fix(tests): update error assertion for node 9.2.0+

src_docs/source/test_results/node/utxo_hd_9_1_1.rst
Added regression test results for UTXO-HD on version 9.1.1. The results include disk and memory backend tests for Conway 9 and Conway 10, as well as other tests like rollback, P2P dynamic block production, and upgrade testing.
=> feat(docs): add UTXO-HD regression test results

cardano_node_tests/tests/tests_conway/test_guardrails.py
Updated the `check_invalid_proposals` function to handle a new error message "expecting white space or digit" introduced in node 9.2.0+. This ensures the test correctly identifies invalid proposals.
=> fix(tests): handle new error message in guardrails test

.github/node_upgrade_pytest.sh, cardano_node_tests/tests/test_node_upgrade.py, src_docs/source/test_results/nightly_system_tests.rst
This commit updates the upgrade testing setup to use the Conway era instead of the Babbage era. The documentation is updated to reflect these changes.
=> feat: upgrade testing from Conway era

README.md
This commit updates all references from Babbage to Conway in the README.md file. This includes instructions for preparing the testing environment, starting and stopping the cluster instance, configuring test runs, and running the development cluster. The changes ensure consistency with the latest cluster era.
=> feat: update cluster era references to Conway

cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_tx_negative.py, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/clusterlib_utils.py
The only usable protocol in Conway is full Cardano mode.
This commit removes the protocol mode checks and arguments from the test cases and utility functions. The protocol mode is no longer required, simplifying the code and reducing redundancy.
- Removed protocol checks in test_cli.py and test_tx_negative.py
- Removed protocol arguments in cluster_nodes.py and clusterlib_utils.py
=> refactor: remove protocol mode checks and arguments

cardano_node_tests/tests/delegation.py, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/configuration.py
- Removed obsolete testnet types from cluster_nodes.py
- Removed unused testnet pool IDs from configuration.py
- Added new preview pool IDs in delegation.py
- Updated references to use the new preview pool IDs
=> refactor: update testnet pool IDs and remove unused ones

cardano_node_tests/tests/test_env_network_id.py
Updated the `magic_args` for the `arg_missing` scenario in the `test_env_network_id.py` test file to include `--cardano-mode`. This assures that the expected error message is returned.
=> fix(tests): update magic_args for missing arg scenario

cardano_node_tests/tests/test_cli.py
Add a call to `cluster.create_pparams_file()` in the `calculate-min-fee` test method of the `TestCLI` class. This ensures that the protocol parameters file is created before running the test, which is necessary for the test to execute correctly and for the expected error message to be returned.
=> feat(tests): add create_pparams_file in TestCLI

cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_pool_saturation.py, cardano_node_tests/tests/test_staking_no_rewards.py, cardano_node_tests/tests/test_staking_rewards.py, cardano_node_tests/tests/test_tx_many_utxos.py, cardano_node_tests/tests/test_update_proposals.py, cardano_node_tests/tests/tests_plutus/test_delegation.py
Make sure that the "order" and "long" markers are used only on individual tests, not on class or module level, where it makes sense.
=> refactor: review "order" marker

cardano_node_tests/tests/common.py, cardano_node_tests/tests/test_configuration.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_pools.py, pyproject.toml
Introduce ORDER5_BYRON and LONG_BYRON markers to conditionally apply pytest marks based on the configuration. This change helps to avoid setting priority for tests when the it is not needed, because the tests run on setup where it is fast to respin the local testnet.
Also, add a new "noop" placeholder marker to the pyproject.toml file.
=> feat(tests): add conditional markers for Byron tests

.github/regression.sh, .github/setup_venv.sh, cardano_node_tests/tests/conftest.py
- Introduced `_cleanup_testnet` function to handle testnet cleanup.
- Modified the trap to call `_interrupted` function on SIGINT.
- Added `pytest_keyboard_interrupt` hook to create a status file.
- Updated `setup_venv.sh` to create venv only if it doesn't exist.
- Enhanced `testenv_setup_teardown` to handle interrupted test runs.
=> feat: add testnet cleanup on interrupted test run

cardano_node_tests/utils/logfiles.py
Added logic to ignore "TrHandshakeClientError" on testnets. This error can occur when some clients are outdated or using incorrect network magic. This change helps to reduce noise in the logs and focus on relevant issues.
=> fix(logfiles): ignore handshake errors on testnet

cardano_node_tests/tests/test_blocks.py
Make sure a testnet is at least in epoch 2. We want to make sure all pools are already forging blocks.
=> Block production epoch

cardano_node_tests/tests/tests_conway/test_hardfork.py
Added an assertion to check that the major protocol version is still 9 in the ratification epoch.
=> feat(tests): add assertion for protocol major version

cardano_node_tests/tests/test_tx_many_utxos.py, cardano_node_tests/tests/tests_conway/test_drep.py
Fund large amounts of tADA from the main faucet instead of from the user faucets. User faucets don't need to have that much tADA.
=> fix(tests): fund large amounts of tADA from main faucet

cardano_node_tests/utils/clusterlib_utils.py
The `fund_from_genesis` function and related imports have been removed from `clusterlib_utils.py` as they are no longer used in the codebase.
=> refactor: remove unused fund_from_genesis function

README.md, prepare_test_env.sh
Running test env setup recreates the whole test env. Sometimes it is useful to activate the same test env in multiple shells. This change enables that.
=> feat: make test env setup reusable in another shells

cardano_node_tests/tests/tests_conway/test_guardrails.py
Refactor governance guardrail tests to use subtests for each scenario.
This makes it possible to schedule all guardrails tests to a single pytest worker, and respin the cluster instance immediately after the tests are finished.
- Removed individual test methods in TestGovernanceGuardrails class
- Added get_subtests function to yield guardrail test scenarios
- Updated test_guardrails method to run subtests
=> refactor(tests): use subtests for guardrail scenarios

cardano_node_tests/tests/tests_conway/test_guardrails.py
Added @pytest.mark.long to the test_guardrails method in TestGovernanceGuardrails class to indicate that it is a long-running test. This helps in scheduling tests based on their execution time.
=> feat(tests): mark test_guardrails as long running

cardano_node_tests/tests/tests_plutus_v2/test_spend_collateral_build.py
With cardano-cli 10.0.0.0, tokens on collateral UTxO are allowed even when return collateral txout is not specified.
=> feat(tests): add test to return collateral with tokens

cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/tests/delegation.py, cardano_node_tests/tests/test_delegation.py, cardano_node_tests/tests/test_staking_rewards.py
Updated the cluster scripts and test files to delegate to `always_abstain` DRep. This is needed in protocol version 10 to make withdrawals work.
=> feat: update delegation of stake addresses to include vote delegation

.github/workflows/regression-dbsync.yaml, .github/workflows/regression.yaml
- Added conway 9 and conway 10 options to cluster era in regression-dbsync.yaml
- Set default cluster era to conway 9 in regression-dbsync.yaml
- Added conway option to tx era in regression-dbsync.yaml
- Removed older eras (alonzo, mary, allegra, shelley) from tx era in both regression-dbsync.yaml and regression.yaml
- Added conway only option to markexpr in regression-dbsync.yaml
=> feat(workflows): update regression workflows for conway era

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/utils/governance_setup.py
Setup DReps in cluster scripts instead of in the framework.
- Introduced NUM_DREPS and DREP_DELEGATED variables.
- Added logic to generate DRep keys and registration certificates.
- Updated transaction building to include DRep registration.
- Modified governance setup to load DReps and DRep users.
- Adjusted protocol parameters and transaction amounts.
=> feat(cluster): add DRep support to cluster scripts

cardano_node_tests/cluster_scripts/conway/start-cluster
Added functionality to delegate pool rewards to alwaysAbstain DRep in the hard fork cluster scripts.
This includes generating vote-delegation certificates for each pool and incorporating them into the transaction build and sign steps.
=> feat(cluster): delegate pool reward to alwaysAbstain DRep

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
This commit removes redundant cardano-cli protocol-parameters queries from various cluster start scripts. The queries were previously used to calculate fee, but they are no longer necessary for the current workflow. This change helps streamline the scripts and improve their efficiency.
=> feat: remove redundant protocol-parameters queries

cardano_node_tests/tests/issues.py, cardano_node_tests/tests/test_cli.py
Added a new test to verify that the `query tip` command is available at the top level in the CLI. This test ensures that the command is accessible and returns the expected keys in the output. Also, added a blocker for issue 953 in the `cardano-cli` repository.
=> feat(tests): add test for top-level `query tip` command

cardano_node_tests/tests/test_cli.py
Refactor the `test_toplevel_query_tip` test to `test_toplevel_queries` and parametrize it to cover multiple CLI query commands. This change improves test coverage by checking the availability of various queries at the top level.
Commands covered:
- protocol-parameters
- tip
- stake-pools
- stake-distribution
- stake-address-info
- utxo
- ledger-state
- protocol-state
- stake-snapshot
- leadership-schedule
- kes-period-info
- pool-state
- tx-mempool
- slot-number
=> feat(tests): parametrize CLI query tests

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Combined certs are supported only by cardano-cli bundled with node 10.1.1. Create old certificates on PV9 for backwards compatibility.
=> feat(cluster): create combined certs only for Conway PV10

cardano_node_tests/tests/test_rollback.py, scripts/test_rollbacks.sh
The `securityParam` is too low on local testnet with short epochs.
Also run `test_permanent_fork` only on testnet with short epochs, as `securityParam` is too high on mainnet like testnet.
=> feat(tests): run test_consensus_reached only on mainnet

cardano_node_tests/tests/test_reconnect.py, scripts/test_node_reconnect.sh
Added a skip condition to the `test_metrics_reconnect` test to ensure it does not run on testnet with short epochs.
=> feat(tests): force mainnet_fast for reconnect test

cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Split the registration and vote delegation certificates into separate commands for compatibility with older node releases. Updated the scripts to generate individual registration and vote delegation certificates for each delegatee stake address.
=> feat(cluster): split registration and delegation certs

.github/node_upgrade_pytest.sh
Updated the cardano-cli command to include 'latest' for querying the tip with the testnet magic.
=> fix(node_upgrade_pytest.sh): update cardano-cli command

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
- Removed hardcoded POOL_COST value from start-cluster scripts.
- Added logic to fetch POOL_COST from genesis.spec.json.
- Set default POOL_COST to 600 if fetched value is 0.
=> feat: update POOL_COST initialization logic

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Updated the start-cluster scripts to use braces for variable expansion in cases where the variable is part of a string.
=> fix(start-cluster): unify varaibles notation

cardano_node_tests/tests/tests_conway/test_update_plutusv2_builtins.py
Added a check in the test to skip if the PlutusV2 cost model has already been updated. This prevents redundant updates and ensures the test runs only when necessary.
=> feat(tests): add check for updated PlutusV2 cost model

cardano_node_tests/tests/plutus_common.py, cardano_node_tests/tests/tests_plutus/test_mint_build.py
- Change FAILING_MINTING_BITWISE_SCRIPTS_V3 to tuple instead of generator
- Update pytest parametrize ids to use script_file.stem instead of name
This ensures better readability and consistency in test identifiers.
=> fix(tests): update script file identifiers

.github/workflows/regression-dbsync.yaml, .github/workflows/regression.yaml, cardano_node_tests/tests/tests_plutus/test_mint_build.py, pyproject.toml
- Added `team_plutus` marker to the regression-dbsync and regression workflows.
- Marked relevant tests in `test_mint_build.py` with `@pytest.mark.team_plutus`.
- Updated `pyproject.toml` to include the new `team_plutus` marker.
=> feat: add team_plutus marker to tests and workflows

cardano_node_tests/utils/dbsync_check_tx.py
Updated the `check_tx_collaterals` function to filter transaction collaterals by Lovelace. This change ensures that only collateral UTxOs with Lovelace are considered, while multi-assets in collateral inputs are not yet supported.
TODO: Add support for multi-assets in collateral inputs.
=> fix(dbsync): filter tx collaterals by Lovelace

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Changed the command from mv to cp for genesis.conway.spec.pv10.json in start-cluster scripts. This ensures the original file remains intact while copying it to the target directory. This change affects the conway, conway_fast, and mainnet_fast cluster scripts.
=> feat(cluster): change mv to cp for genesis spec files

cardano_node_tests/tests/test_kes.py
Removed the redundant `SKIPIF_NOT_HF_SHORTCUT` decorator and replaced it with an inline skipif condition in the `TestKES` class.
Removed unused `MAX_INT_VAL` constant.
=> refactor(tests): remove redundant `SKIPIF_NOT_HF_SHORTCUT`

cardano_node_tests/tests/test_kes.py
Updated the comment in test_kes.py to clarify the slot number where KES expires when using `cluster_kes`. This improves the readability and understanding of the code.
=> fix(tests): update KES expiration comment

cardano_node_tests/tests/tests_conway/test_pparam_update.py, cardano_node_tests/utils/dbsync_utils.py
Updated `check_conway_param_update_enactment` to accept pparams instead of full gov state for better efficiency.
Updated function parameters in `check_conway_param_update_enactment` and `map_params_to_db_convention` for better clarity and consistency.
=> refactor: make `check_conway_param_update_enactment` accept pparams

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Added the -f (force) flag to the cp command in the start-cluster scripts for conway, conway_fast, and mainnet_fast. This ensures that the genesis.conway.spec.pv10.json file is copied even if it already exists in the destination directory.
=> fix(cluster-scripts): add force flag to cp command

cardano_node_tests/cluster_scripts/testnets/start-cluster
Added a symlink for the genesis-conway.json file in the start-cluster script to ensure it is correctly referenced in the Shelley directory.
=> feat(cluster): add conway genesis file symlink

scripts/test_node_ipc_shutdown.sh
Add a new script `test_node_ipc_shutdown.sh` to test the IPC shutdown mechanism of the Cardano node. This script is intended to run on long running testnets such as Preview.
=> feat(scripts): add test_node_ipc_shutdown.sh script

cardano_node_tests/tests/test_node_upgrade.py
The commit removes variables `BASE_REVISION` and `UPGRADE_REVISION` from the `test_node_upgrade.py` file. The revisions don't need to be version strings, but also branches or commit hashes. Handling the revisions as version strings can be problematic.
=> refactor: do not depend on revision variables

.github/env_nightly_upgrade
The BASE_TAR_URL was incorrectly duplicated in the env_nightly_upgrade file. This commit removes the duplicate and ensures the URL is correctly formatted.
=> fix(env): correct BASE_TAR_URL in env_nightly_upgrade

cardano_node_tests/tests/test_node_upgrade.py
Removed unnecessary epoch interval wait before submitting proposal and voting in test_node_upgrade.py. The
`conway_common.propose_pparams_update` waits for the epoch interval.
=> fix(tests): remove redundant epoch interval wait

.github/node_upgrade.sh, .github/regression.sh, .github/workflows/regression_reusable.yaml, .github/workflows/upgrade_reusable.yaml
This commit adds the "Script setup" group in the `node_upgrade.sh` and `regression.sh` scripts. This change improves the readability of the CI logs by clearly delineating the setup phase from the rest of the script execution.
=> feat: add group for script setup in CI scripts

.github/node_upgrade.sh, .github/regression.sh, .github/source_cardano_cli.sh, .github/source_dbsync.sh, .github/source_plutus_apps.sh
Updated the group names in various shell scripts to provide more clarity and consistency. This includes changes in node_upgrade.sh, regression.sh, source_cardano_cli.sh, source_dbsync.sh, and source_plutus_apps.sh. The new group names better reflect the steps being performed in each section.
Remove groups from sourced scripts and move them to the top level script. Groups cannot be nested, and having them just in the top level script makes them more manageable.
=> refactor: update group names in shell scripts

cardano_node_tests/tests/tests_conway/test_guardrails.py
Added a call to governance_utils.wait_delayed_ratification in the cluster_with_constitution function to ensure proper handling of delayed ratification in the test_guardrails.py file.
=> feat(tests): add delayed ratification wait in guardrails

flake.lock
- Updated CHaP to rev 25591f43ab943d5a070db5e8a2b9ff3a499d4d92
- Updated cardano-node to 10.1.2
=> chore: update flake.lock dependencies

flake.nix
- Added a TODO comment for removing sync tests once moved to a separate repo
- Removed compatibility code for cardano-node 1.34.1
=> chore(flakes): update devShells and remove legacy compat

.github/workflows/repo_tests.yaml, flake.nix, setup_dev_venv.sh
Updated the base dev shell in flake.nix to use Python 3.11 instead of the default Python 3.10. This change ensures that all dependencies and tools in the base shell are compatible with Python 3.11.
=> feat: update base dev shell to use Python 3.11

.pre-commit-config.yaml
Updated the following pre-commit hooks to their latest versions:
- pre-commit-hooks from v4.6.0 to v5.0.0
- ruff-pre-commit from v0.6.3 to v0.7.3
- markdownlint-cli from v0.41.0 to v0.42.0
This ensures we are using the latest features and fixes.
=> chore: update pre-commit hooks to latest versions

README.md
The README file has been updated to remove the specific Python version requirement (v3.8 or newer) for creating a virtual environment. The `setup_dev_venv.sh` makes sure correct version is used.
=> docs: update Python version requirement in README

cardano_node_tests/tests/tests_conway/test_hardfork.py
Increased the stop buffer in wait_for_epoch_interval to ensure enough time for proposal and votes submission within one epoch.
=> fix(tests): adjust epoch interval buffer in test_hardfork

cardano_node_tests/tests/reqs_conway.py, cardano_node_tests/tests/tests_conway/test_constitution.py
- Added CIP027 to the list of requirements in reqs_conway.py.
- Updated TestConstitution to include a test case for failing to withdraw the deposit from a stake address that is not delegated to a DRep.
=> feat(tests): add CIP027 and failed withdrawal test case

.github/node_upgrade.sh, .github/regression.sh
Special keywords like "::endgroup::" in debug output seem to confuse GHA from time to time. Try to hide the keyword using hexadecimal representation.
=> fix(github-actions): hide special keywords in debug output

.github/node_upgrade.sh, .github/regression.sh
Attempt no. 7 to make GHA grouping work reliably for all workflows. Having debug output after group ends seem to confuse the parser. This commit disables xtrace at the group beginning and end.
=> refactor: turn xtrace off when printing out grouping strings

cardano_node_tests/utils/testnet_cleanup.py
Replaced contextlib.suppress with try-except blocks to handle clusterlib.CLIError exceptions. This change improves error logging by providing specific error messages when exceptions occur.
=>  refactor: replace contextlib.suppress with try-except

.github/node_upgrade.sh, .github/regression.sh
Attempt no. 8 to make GHA grouping work reliably for all workflows. Having debug output seems to confuse the GHA groups parser, and some of the debug output leaks out of the groups. I've tried several different attempts to mitigate this behavior, unsuccessfully. In this commit, I'm turning debug output off alltogether. The script is stable, we don't have much use for the debug output anyway.
=> refactor: turn xtrace off for CI scripts

.github/grep_errors.sh, .github/node_upgrade.sh, .github/regression.sh, .github/source_dbsync.sh
Removed multiple redundant `df -h .` commands from various CI scripts. Added a check for the existence of the `stop_postgres` command before attempting to stop PostgreSQL.
=> refactor(ci): cleanup CI scripts output

flake.nix
Removed old missing inputs from flake.nix to clean up the configuration.
=> chore: remove missing nix inputs

flake.nix
Refactored flake.nix to introduce nodePkgs variable for cardano-node packages. This change improves readability and maintainability by replacing repeated cardano-node package references with nodePkgs.
=> feat: refactor flake.nix to use nodePkgs variable

flake.nix
The python devshell has been removed from flake.nix as the sync tests are being fully moved to a separate repository. This change cleans up the flake configuration by removing the unnecessary python shell.
=> chore(nix): remove python devshell from flake.nix

.github/node_upgrade_pytest.sh
Removed the 'set -x' option from the node_upgrade_pytest.sh script to disable xtrace and reduce verbosity in CI output.
=> chore(ci): remove xtrace from node upgrade script

cardano_node_tests/tests/test_protocol.py
- Removed unused imports and constants related to protocol param keys
- Updated `PROTOCOL_PARAM_KEYS` to include new parameters for Conway
- Removed conditional logic for protocol param keys based on versions
=> feat(protocol): update protocol param keys for Conway

cardano_node_tests/tests/test_governance.py
Make the poll tests work in Conway.
- Update docstrings to reflect pre-Conway governance functionality
- Remove version checks for Babbage transaction era
- Replace direct transaction build and submit calls with utility function
- Adjust error assertions to include new possible error messages
=> refactor(tests): update old pre-Conway poll tests

cardano_node_tests/tests/tests_conway/test_drep.py
Refactor the test_drep.py to use the get_drep_reg_record function from governance_utils. This change simplifies the code by removing manual steps for generating drep registration certificates and deposit amounts. The function handles these internally, making the test code cleaner and more maintainable.
=> feat: use get_drep_reg_record in test_drep.py

cardano_node_tests/utils/logfiles.py
Added OffChainPoolFetchError and OffChainVoteFetchError to the list of ignored errors in logfiles.py. The table names are matching the searched error strings, but are not errors.
=> feat: add DB-Sync table names to error ignore list

.github/workflows/regression_reusable.yaml, .github/workflows/upgrade_reusable.yaml
Replaced the arrow symbols (🠉) with a simpler arrow (↑) in the workflow names for better compatibility with fonts with limited set of unicode characters.
=> chore: replace arrow symbols in workflow names

.github/workflows/regression_reusable.yaml, .github/workflows/upgrade_reusable.yaml
- Changed the arrow symbol in the names of upload steps in the regression and upgrade workflows from "↑" to "↟" for better clarity.
=> feat(ci): update artifact upload arrow

cardano_node_tests/tests/plutus_common.py
Added a condition to skip the Plutus transaction cost check when running on testnets. This is because the costs are calibrated only for the local testnet environment.
=> feat: skip Plutus cost check on testnets

cardano_node_tests/utils/faucet.py
Updated the `fund_from_faucet` function to accept `None` as a valid value for the `amount` parameter. If `amount` is `None`, it defaults to 1,000,000,000. This change ensures better flexibility in specifying the amount to be funded from the faucet.
=> fix(faucet): allow None as amount parameter

cardano_node_tests/utils/submit_api.py
- Added retry logic to handle request timeouts when posting CBOR data to the submit API.
- Introduced a delay with random sleep time between retries to avoid overwhelming the server.
=> fix(submit_api): handle timeout and resubmit transaction

Makefile
Reduced the number of test threads for the testnets target in the Makefile from 20 to 15. This change is intended to optimize the stability of the tests.
=> chore: update testnets thread count to 15

cardano_node_tests/tests/plutus_common.py
Updated the SECP256K1_ECDSA_LOOP_COST and SECP256K1_SCHNORR_LOOP_COST values in plutus_common.py to reflect the new execution costs.
=> feat: increase SECP256K1 loop costs

cardano_node_tests/tests/tests_conway/test_drep.py
- Modified get_payment_addr to use caching_key conditionally.
- Adjusted payment_addr to handle different dRepDeposit values.
=> feat: don't cache fixture when deposit too high

cardano_node_tests/tests/tests_conway/test_drep.py
- Improved readability and clarity of docstrings by rephrasing some sentences.
- Updated docstrings in test_drep.py to consistently use "DRep" instead of "drep".
- Ensured all references to DRep are capitalized for consistency.
=> fix(tests): unify DRep docstring and capitalization

cardano_node_tests/tests/issues.py, cardano_node_tests/tests/tests_conway/test_drep.py
- Ensure votes are correctly delegated to the second DRep after the first DRep is retired.
- Check ledger issue 4772.
=> fix(tests): handle DRep retirement in delegation tests

cardano_node_tests/tests/issues.py
Updated the fixed_in version for the cli_904 issue in the cardano-cli repository from 9.5.0.0 to 10.1.2.1. The issue is already fixed in cardano-cli that was not released with cardano-node yet.
=> fix(issues): update fixed_in version for cli issue 904

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/common.py, cardano_node_tests/cluster_management/manager.py
Renamed `_get_resources_from_paths` to `get_resources_from_path` and refactored the function to use a helper function `_get_res` for better readability and maintainability.
=> refactor: rename and refactor resource functions

cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_ledger_state.py
Corrected the key names for stake set in test_cli.py and test_ledger_state.py to match the expected values. This fixes issues with missing keys in stake snapshots and ensures the tests run correctly.
=> fix(tests): correct stake set key names in tests

cardano_node_tests/cluster_management/resources.py, cardano_node_tests/tests/tests_conway/conftest.py, cardano_node_tests/tests/tests_conway/test_constitution.py, cardano_node_tests/tests/tests_conway/test_guardrails.py, cardano_node_tests/tests/tests_conway/test_pparam_update.py, cardano_node_tests/tests/tests_conway/test_update_plutusv2_builtins.py, cardano_node_tests/tests/tests_plutus/conftest.py, cardano_node_tests/tests/tests_plutus/test_delegation.py, cardano_node_tests/tests/tests_plutus_v2/conftest.py
The hash of current protocol parameters is passed to Plutus scripts, and pparams change after the transaction was built will lead to `PPViewHashesDontMatch` error on tx submit. Therefore we need to mark usage of Plutus scripts, and "lock" Plutus whenewer we are changing pparams.
=> feat: Mark use of Plutus and lock Plutus when changing pparams

cardano_node_tests/tests/test_native_tokens.py, cardano_node_tests/tests/test_staking_no_rewards.py, cardano_node_tests/tests/test_tx_fees.py, cardano_node_tests/utils/faucet.py
Updated method calls from `send_funds` to `send_tx`. The `send_funds` will be deprecated in clusterlib.
Renamed variables in for better clarity and consistency. Replaced 'destinations' with 'txouts' and 'ma_destinations' with 'ma_txouts'.
=> refactor: replace `send_funds` with `send_tx`

cardano_node_tests/tests/tests_conway/test_drep.py
There's no need to cache DReps that are created only for single test.
=> refactor(tests): don't cache DReps created in test

.github/source_cardano_cli.sh, .github/source_dbsync.sh, .github/source_plutus_apps.sh
Replaced pushd/popd with cd in GitHub scripts for better readability and consistency. Return to original paths.
=> refactor(github): replace pushd/popd with cd

cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
Added check that duplicated proposals are discarded when building a transaction.
=> feat(treasury_withdrawals): check discard duplicate proposals

cardano_node_tests/tests/test_pools.py
The metadata URL was changed to a valid URL by mistake in one of the previous PRs.
Also we can no longer use `transaction build` for this test, as `build` now checks metadata availability. We can still use `build-raw`.
=> fix: fix metadata unavail test

cardano_node_tests/tests/test_tx_unbalanced.py, cardano_node_tests/tests/tests_plutus/test_mint_negative_build.py, cardano_node_tests/tests/tests_plutus/test_spend_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_ref_scripts_build.py
Updated error assertions in various test files to accommodate new error messages introduced in CLI version 10.1.1.0+. This ensures compatibility with both older and newer versions of the CLI.
- Updated test_tx_unbalanced.py to check for "Value must be positive in UTxO"
- Updated test_mint_negative_build.py to check for new error messages
- Updated test_spend_build.py to handle new execution failure messages
- Updated test_spend_negative_build.py to include new error assertions
- Updated test_spend_ref_scripts_build.py to check for new error messages
=> fix(tests): update error assertions for CLI 10.1.1.0+

README.md
- Removed Black badge from README
- Updated formatting tool reference from Black to Ruff
- Ensured consistency with Google Python Style Guide
=> chore: update README to replace Black with Ruff

cardano_node_tests/utils/clusterlib_utils.py
- Refactored `get_snapshot_rec` to support only dict format in node 8.4+
- Refactored `get_snapshot_delegations` to handle only dict format in node 8.4+
- Removed old list-based format handling
=> refactor(utils): update snapshot format handling

.pre-commit-config.yaml, cardano_node_tests/cluster_management/manager.py, pyproject.toml
- Update ruff-pre-commit to v0.8.3 and markdownlint-cli to v0.43.0
- Reformat code using the updated ruff
- Update pyproject.toml to remove deprecated ignores
=> chore: update pre-commit hooks

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/netstat_tools.py
It can happen that leftover processes from previous cluster instance prevent new cluster instance from starting. This change makes sure to kill all the leftover processes.
- Introduced `netstat_tools` module to handle netstat operations.
- Enhanced process killing logic to handle leftover processes more robustly.
- Moved `_kill_supervisor` and `_get_netstat_out` functions to the new module.
- Updated `ClusterGetter` to use the new `netstat_tools` functions.
=> feat(cluster_management): kill all leftover processes

cardano_node_tests/cluster_management/netstat_tools.py
Added shell=True to the run_command function in netstat_tools.py to ensure the netstat command is executed correctly. The command has pipe, so shell is needed.
=> fix(netstat_tools): add shell=True to run_command

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
- Add retries for `query utxo` command to handle intermittent failures
- Ensure `txhash`, `txix`, and `amount` are valid before processing
- Adjust formatting for better readability and maintainability
=> fix(cluster_scripts): improve query utxo reliability

cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py
Use `build-raw` instead of `build` to workaround an error message that deposit return stake address is not registered.
=> fix(treasury_withdrawals): use `build-raw` in bootstrap

cardano_node_tests/cluster_management/netstat_tools.py
- Replace tab characters with spaces in netstat output to ensure consistent line splitting.
- Add whitespace to the end of each port number to avoid matching a port number that is a prefix of another port number.
=> fix: avoid matching a port number that is prefix of other port number

cardano_node_tests/cluster_management/netstat_tools.py
The netstat command was modified to exclude the 'CLOSE' state from the output. This change ensures that only 'LISTEN' and 'TIME_WAIT' states are included, and so no client connection can be matched.
=> fix(netstat_tools): remove CLOSE from netstat command

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/netstat_tools.py
- Introduced a logging function to capture messages during the killing of leftover processes in `netstat_tools.py`.
- Updated `kill_old_cluster` to accept a logging function and log messages to `scheduling.log`.
- Modified `cluster_getter.py` to pass a logging function to `kill_old_cluster`.
=> feat: add logging to netstat tools for process killing

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/utils/framework_log.py, cardano_node_tests/utils/logfiles.py, cardano_node_tests/utils/temptools.py
- Moved framework logging functions from `logfiles.py` to new `framework_log.py` module.
- Updated imports and references to use the new `framework_log` module.
- Adjusted `temptools.py` to use `IS_XDIST` directly from `os.environ`.
=> refactor(logging): move framework logging to separate module

Makefile, cardano_node_tests/tests/tests_conway/conway_common.py, cardano_node_tests/tests/tests_conway/test_drep.py, cardano_node_tests/utils/governance_setup.py, pyproject.toml
- Update Makefile to use pytype with -k and -j auto options
- Convert committee value to dict in conway_common.py and governance_setup.py
- Add assertion for drep_data in test_drep.py
- Update Python version to 3.11 in pyproject.toml for pytype and mypy
=> fix(pytype): resolve type errors and update Python version

cardano_node_tests/tests/test_tx_basic.py, cardano_node_tests/tests/test_tx_metadata.py, cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py
- Replace `create_payment_addr_records` with `get_payment_addr` in `test_tx_basic.py` and `test_tx_metadata.py`
- Update `test_committee.py` to use `get_payment_addr` with caching key
- Modify `test_spend_negative_raw.py` to use `get_payment_addrs` for funding Plutus scripts
=> refactor: update address creation and funding methods

cardano_node_tests/cluster_management/netstat_tools.py
- Simplified netstat command to use `netstat -plnt` for listening services
- Removed unnecessary shell execution in netstat command
- Adjusted wait logic for closing connections in TIME_WAIT state
- Increased sleep duration to ensure connections are properly closed
=> refactor: update netstat command and improve wait logic

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/manager.py
- Added `ports` property to `ClusterGetter` to return port mappings for the current cluster instance.
- Removed `ports` property from `ClusterManager` as it is now handled by `ClusterGetter`.
- Updated logging to include port mappings when cluster fails to start.
=> feat(cluster): add ports property to ClusterGetter

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway/stop-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/stop-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/stop-cluster, cardano_node_tests/cluster_scripts/testnets/start-cluster, cardano_node_tests/cluster_scripts/testnets/stop-cluster, cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/cluster_scripts.py
Use unix socket to communicate with supervisord instead of HTTP socket. This reduces number of http connections in TIME_WAIT state during cluster shitdown.
- Added `SUPERVISORD_SOCKET_PATH` to cluster scripts.
- Updated supervisor configuration to use unix socket.
- Modified `supervisorctl` commands to use unix socket.
- Updated `cluster_nodes.py` to support unix socket for supervisorctl.
- Commented out inet_http_server configuration in `cluster_scripts.py`.
=> feat: add supervisord unix socket support

cardano_node_tests/tests/kes.py, cardano_node_tests/tests/test_kes.py, cardano_node_tests/tests/test_metrics.py, cardano_node_tests/tests/test_reconnect.py, cardano_node_tests/utils/http_client.py, cardano_node_tests/utils/submit_api.py
Reuse HTTP connections to avoid number of connections in TIME_WAIT status.
- Removed direct imports of `requests` in test files.
- Added `http_client` module to provide a global HTTP client session.
- Updated test files to use the global HTTP client session.
- Modified `submit_api.py` to use the global HTTP client session.
=> feat: replace requests with global HTTP client

cardano_node_tests/tests/test_pools.py, cardano_node_tests/tests/tests_conway/test_drep.py
Increased the timeout for dbsync_utils.retry_query from 300 to 360 seconds in test_pools.py and test_drep.py to ensure tests have sufficient time to complete.
=> feat(tests): increase query timeout to 360 seconds

garnix.yaml
Garnix is now enabled in our repo, but we don't need it.
=> feat: disable garnix

.reponotes
The symlink was included in a commit by mistake.
=> feat: remove .reponotes symlink

cardano_node_tests/tests/delegation.py
Added a new set of preprod pool IDs to the delegation tests in `cardano_node_tests/tests/delegation.py`. This allows the tests to use hardcoded pool IDs for the preprod testnet, similar to the existing setup for the preview testnet.
=> feat(tests): add preprod pool IDs for delegation tests

cardano_node_tests/tests/conftest.py
Updated warning messages in conftest.py to indicate the use of custom paths for `cardano-cli` and `cardano-node` instead of nix store paths.
=> fix(tests): update warning messages for custom paths

cardano_node_tests/tests/data/test_tx_metadata_both_tx_body_json.out, cardano_node_tests/tests/data/test_tx_metadata_both_tx_json.out, cardano_node_tests/tests/test_cli.py
- Updated test_tx_metadata_both_tx_body_json.out to include "datums" and "scripts" fields.
- Updated test_tx_metadata_both_tx_json.out to include "datums" and "scripts" fields.
- Modified test_cli.py to handle new "datums" field and ensure compatibility with the updated output format.
=> feat: update tx view golden files

cardano_node_tests/tests/test_native_tokens.py
Updated the error message assertions in test_native_tokens.py to handle new error messages introduced in cardano-node 10.2.0.0.
=> fix(tests): update error message assertions

README.md, setup_dev_venv.sh
Updated README.md and setup_dev_venv.sh to replace `poetry shell` with `source "$(poetry env info --path)"/bin/activate` for activating the virtual environment.
=> refactor: replace `poetry shell` with `source` command

Makefile, README.md, scripts/deploy_doc.sh
- Rename Makefile targets for building and deploying documentation
- Update README.md to reflect new Makefile targets
- Modify deploy_doc.sh script to use new Makefile targets
=> feat: update doc build and deploy process

Makefile, README.md
Added '@' to the check_dev_env target in the Makefile to silence its output. Updated README.md to reflect this change by removing the script call from the example output.
=> fix(Makefile): silence check_dev_env output

cardano_node_tests/cluster_management/cluster_getter.py
Corrected the logger string arguments in cluster_getter.py to ensure proper formatting of the error message when a cluster instance fails to start.
=> fix(cluster_management): correct logger string arguments

cardano_node_tests/utils/logfiles.py
Reordered and updated error patterns in logfiles.py to ensure correct matching also on node 10.2, where some error messages now has "IOException" instead of "MuxIOException".
=> fix(logfiles): update ignored error patterns

flake.lock
Updated the flake.lock file to point to the latest nixpkgs version. This includes changes to the lastModified, narHash, rev, and ref fields to reflect the new version.
=> chore: update flake.lock to latest nixpkgs

cardano_node_tests/tests/issues.py
Updated the `fixed_in` field for CLI issue 1023 to reflect that it is fixed in cardano-cli release that comes after 10.3.0.0.
=> feat: mark CLI issue 1023 as fixed in 10.3.0.1+

cardano_node_tests/utils/logfiles.py
- Changed splitlines(keepends=True) to splitlines(keepends=False)
- Updated logic to handle incomplete lines at the end of chunks
=> fix(logfiles): handle incomplete lines without preserving endings

.github/regression.sh
Moved the report files to the root directory only if the report file exists and if the tests are running on GHA.
=> fix: conditionally move reports to root dir

.github/node_upgrade_pytest.sh, cardano_node_tests/tests/test_node_upgrade.py, src_docs/source/test_results/nightly_system_tests.rst
- Configured the testnet to start in PV10 in node_upgrade_pytest.sh
- Disabled tests not needed for PV10 in test_node_upgrade.py
- Updated documentation for nightly system tests to reflect PV10
=> feat: upgrade testing now starts in protocol version 10

cardano_node_tests/utils/cluster_nodes.py, cardano_node_tests/utils/framework_log.py, cardano_node_tests/utils/helpers.py, cardano_node_tests/utils/temptools.py
Replaced the custom `callonce` decorator with `functools.cache` in multiple utility modules. This simplifies the code and leverages the built-in caching mechanism provided by Python's standard library.
=> refactor(utils): replace custom callonce with functools.cache

cardano_node_tests/tests/plutus_common.py, cardano_node_tests/tests/test_native_tokens.py, cardano_node_tests/tests/test_staking_rewards.py, cardano_node_tests/tests/tests_plutus/spend_build.py, cardano_node_tests/tests/tests_plutus/spend_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_raw.py, cardano_node_tests/tests/tests_plutus_v2/spend_build.py, cardano_node_tests/tests/tests_plutus_v2/spend_raw.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_collateral_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_collateral_raw.py, cardano_node_tests/utils/clusterlib_utils.py
Renamed the TokenRecord class to NativeTokenRec across multiple files for better clarity and consistency.
Moved Token class to clusterlib_utils as it is not Plutus speciffic.
=> refactor: rename TokenRecord, move Token

.github/source_cardano_cli.sh, .github/source_plutus_apps.sh
Added the --no-write-lock-file option to nix build commands in source_cardano_cli.sh and source_plutus_apps.sh to prevent writing lock files during the build process.
Changes:
- Modified .github/source_cardano_cli.sh
- Modified .github/source_plutus_apps.sh
=> feat: add --no-write-lock-file to nix build commands

cardano_node_tests/tests/plutus_common.py, cardano_node_tests/tests/tests_plutus/spend_build.py, cardano_node_tests/tests/tests_plutus/spend_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_build.py, cardano_node_tests/tests/tests_plutus/test_spend_compat_build.py, cardano_node_tests/tests/tests_plutus/test_spend_compat_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_datum_build.py, cardano_node_tests/tests/tests_plutus/test_spend_datum_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py, cardano_node_tests/tests/tests_plutus/test_spend_raw.py, cardano_node_tests/tests/tests_plutus_v2/spend_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_collateral_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_compat_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_datum_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_ref_inputs_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_ref_scripts_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_secp256k1_build.py, cardano_node_tests/tests/tests_plutus_v3/test_spend_build.py, cardano_node_tests/utils/clusterlib_utils.py
- Updated execution costs for guessing game scripts
- Added `amount` parameter to `_build_fund_script` and `_build_spend_locked_txin`
- Adjusted test cases to use the new `amount` parameter
- Ensured additional funds are added to cover fees and Lovelace change
- Refactored to include payment address for additional funds
=> feat(plutus): minimize locked funds on spend script addresses

cardano_node_tests/tests/test_cli.py
Reordered the error message assertions in `test_cli.py` to ensure the "Invalid key" error is checked first. This improves the clarity and accuracy of the test failure messages.
=> fix(tests): correct order of error message assertions

cardano_node_tests/tests/tests_plutus_v2/test_spend_raw.py
- Add optional db-sync transaction check in `TestLockingV2.test_spend_locked_utxo`
=> feat(tests): add db-sync check for transaction spending

cardano_node_tests/tests/test_scripts.py, cardano_node_tests/utils/clusterlib_utils.py
Modified tests to use additional UTxO for covering fees in order to be able to spend all funds locked on script UTxOs.
Negative tests that don't spend the locked UTxOs were disabled on long-running testnets.
=> feat: Spend all funds locked on simple scripts

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/common.py, cardano_node_tests/cluster_management/manager.py, cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster
Renamed the start cluster log file from `start_cluster_cmds.log` to `start-cluster.log`.
The log file can be used for all `start-cluster` logging.
=> feat(logging): rename start cluster log file

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster, cardano_node_tests/cluster_scripts/testnets/start-cluster
- Introduced START_CLUSTER_LOG variable in start-cluster scripts
- Updated cardano_cli_log function to use START_CLUSTER_LOG
- Ensured consistent logging path across different cluster scripts
=> feat: add START_CLUSTER_LOG variable for logging

cardano_node_tests/utils/testnet_cleanup.py
Updated the log level from info to debug in testnet_cleanup.py for withdraw_reward, deregister_stake_addr, retire_drep, and return_funds_to_faucet functions to reduce verbosity.
=> refactor: change log level from info to debug

cardano_node_tests/tests/tests_conway/test_drep.py, cardano_node_tests/utils/faucet.py
- Added checks to ensure payment addresses have enough funds for DRep deposits in long-running testnets.
- Updated `fund_from_faucet` default amount formatting.
- Fixed typos and improved variable naming for clarity.
=> fix(tests): ensure sufficient funds for DRep deposits

cardano_node_tests/tests/common.py, cardano_node_tests/tests/test_native_tokens.py, cardano_node_tests/tests/test_scripts.py, cardano_node_tests/tests/test_tx_fees.py, cardano_node_tests/tests/tests_plutus/test_mint_build.py, cardano_node_tests/tests/tests_plutus/test_spend_build.py, cardano_node_tests/tests/tests_plutus/test_spend_datum_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py, cardano_node_tests/tests/tests_plutus_v2/test_mint_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_datum_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_raw.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_ref_inputs_build.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_ref_scripts_build.py, cardano_node_tests/tests/tests_plutus_v3/test_spend_build.py
- Added `is_fee_in_interval` function to `common.py` for checking if the fee is within the expected range on local testnet.
- Replaced `helpers.is_in_interval` with `common.is_fee_in_interval` in various test files to use the new function.
=> feat: check fees only on local testnet

cardano_node_tests/tests/tests_conway/test_drep.py
Increased the deposit amount in the drep test to ensure sufficient funds for testing. This change modifies the amount calculation to deposit_drep_amt * 2 + 10_000_000.
=> feat(tests): double deposit amount in drep test

cardano_node_tests/tests/test_blocks.py, cardano_node_tests/tests/test_dbsync.py, cardano_node_tests/tests/test_pool_saturation.py
Updated test cases to use cluster.g_query.get_epoch and cluster.g_query.get_block_no methods instead of directly accessing the tip dictionary. This improves code readability and maintainability.
=> refactor: use get_epoch and get_block_no methods

cardano_node_tests/cardano_cli_coverage.py
The start-cluster.log can now contain also information other than `cardano-cli` commands.
Previously, an AttributeError was raised when the coverage data was not in the proper format. This change updates the code to log a warning message instead and continue processing. This prevents the program from stopping abruptly due to format issues.
=> fix: handle improper coverage format with warning

cardano_node_tests/utils/logfiles.py
Extended the list of ignored errors for testnet to include TracePromoteWarmBigLedgerPeerAborted. This helps in handling additional error scenarios where clients might be old or using incorrect network magic.
=> fix(utils): extend ignored errors for testnet

cardano_node_tests/cluster_scripts/conway/start-cluster
- Generate stake address registration certificates for both Shelley and Conway eras.
- Generate stake address delegation certificates for both Shelley and Conway eras.
- Generate pool registration certificates for both Shelley and Conway eras.
- Update file paths for generated certificates to include Shelley era identifiers.
=> feat(cluster): add support for Conway era certificates

cardano_node_tests/tests/test_smash.py
- Added `@allure.link` decorator to provide VCS links for test cases.
- Added `@pytest.mark.smoke` to categorize tests as smoke tests.
- Applied `pytestmark` to skip tests if SMASH is not available.
=> feat(tests): add allure links and smoke marks to SMASH tests

cardano_node_tests/tests/conftest.py, cardano_node_tests/utils/configuration.py
- Moved `_check_cardano_node_socket_path` function from `configuration.py` to `conftest.py`.
- Added validation of `CARDANO_NODE_SOCKET_PATH` during pytest configuration.
=> feat(tests): validate CARDANO_NODE_SOCKET_PATH

cardano_node_tests/tests/test_scripts.py
Removed commented-out debug code from test_scripts.py to clean up the codebase. This change ensures that no unnecessary debug statements remain in the production code.
=> refactor(tests): remove forgotten debug code

cardano_node_tests/tests/test_native_tokens.py
These tests should not run on long running testnets, as they leave large amounts of ADA on UTxOs with tokens, which is not currently reclaimed.
=> refactor(tests): remove testnets marker from token tests

cardano_node_tests/testnet_cleanup_info.py, cardano_node_tests/utils/testnet_cleanup.py
- Fixed incorrect variable used in logging uncleaned rewards in `testnet_cleanup_info.py`.
- Updated logging format for rewards in `testnet_cleanup.py` to display in ADA.
=> fix: correct logging of rewards in testnet cleanup

cardano_node_tests/tests/common.py, cardano_node_tests/tests/test_cli.py, cardano_node_tests/tests/test_native_tokens.py, cardano_node_tests/tests/test_reconnect.py, cardano_node_tests/tests/test_rollback.py, cardano_node_tests/tests/test_staking_rewards.py
- Introduced SKIPIF_ON_TESTNET and SKIPIF_ON_LOCAL markers in common.py
- Replaced existing skipif conditions with new markers in test files
- Removed unused imports from test_native_tokens.py and test_staking_rewards.py
=> feat: add skipif markers for testnet and local clusters

cardano_node_tests/tests/tests_plutus/test_mint_build.py, cardano_node_tests/tests/tests_plutus_v2/test_mint_build.py, cardano_node_tests/tests/tests_plutus_v3/test_mint_build.py
Lowered script_fund values in various minting tests across Plutus V1, V2, and V3 to optimize resource usage. This change helps in minimizing the funds required for script execution, ensuring more efficient test runs.
=> fix(tests): reduce script_fund amounts in minting tests

cardano_node_tests/tests/tests_plutus_v2/test_spend_build.py
The test parameter for using tokens is now conditionally skipped on long running testnets. This is to prevent leaving large amounts of ADA on UTxOs with tokens, which are not currently reclaimed.
=> feat(tests): skip token tests on long running testnets

cardano_node_tests/utils/testnet_cleanup.py
Added a dynamic calculation for `witness_count_add` in the `return_funds_to_faucet` function. This ensures a minimum of 2 witnesses or scales based on the number of signing keys divided by 20.
This change fixes the `FeeTooSmallUTxO` error when the fee is not calculated precisely enough.
=> feat(utils): add dynamic witness count adjustment

cardano_node_tests/utils/testnet_cleanup.py
Updated `testnet_cleanup.py` to use `LOGGER.exception` instead of `LOGGER.error` for better error traceability when re-registering or deregistering stake addresses and retiring DReps.
Changes:
- Replaced `LOGGER.error` with `LOGGER.exception` in three functions: `reregister_stake_addr`, `deregister_stake_addr`, and `retire_drep`.
This improves debugging by including stack traces in the logs.
=> fix(utils): log exceptions on stake and DRep operations

cardano_node_tests/utils/testnet_cleanup.py
The `faucet.addr` file is already excluded by the `filter_addr_files` function. This simplifies the logic and ensures all addresses are processed uniformly.
Affected file:
- `cardano_node_tests/utils/testnet_cleanup.py`
=> refactor(testnet_cleanup): remove faucet address check

cardano_node_tests/utils/submit_api.py
The `submit_tx` function now returns the transaction ID (`txid`) instead of `None`.
=> feat(utils): return txid from submit_tx function

cardano_node_tests/testnet_cleanup_info.py, cardano_node_tests/utils/testnet_cleanup.py
Added a new CLI option `--fee` to calculate and display the total fees of signed transactions in the specified directory. Introduced a helper function `fees_info` to compute the fees and log details for each transaction. Updated `testnet_cleanup_info.py` and `testnet_cleanup.py` accordingly.
=> feat(testnet_cleanup): add fee calculation for transactions

cardano_node_tests/utils/custom_clusterlib.py, cardano_node_tests/utils/submit_api.py
Extracted the logic for creating a `.submitted` status file into a dedicated `create_submitted_file` function in `custom_clusterlib.py`.
This improves code reuse and reduces duplication in both `custom_clusterlib.py` and `submit_api.py`.
Affected files:
- `custom_clusterlib.py`
- `submit_api.py`
=> refactor(utils): extract create_submitted_file function

cardano_node_tests/utils/testnet_cleanup.py
Handle the "ConwayDRepNotRegistered" exception when retiring a DRep to avoid logging unnecessary errors. This ensures better error management and cleaner logs.
=> fix(testnet_cleanup): handle unregistered DRep exception

cardano_node_tests/tests/test_staking_rewards.py, cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_conway/test_constitution.py, cardano_node_tests/tests/tests_conway/test_guardrails.py, cardano_node_tests/tests/tests_conway/test_no_confidence.py
Ensure sufficient time to submit votes within one epoch by adding `wait_for_epoch_interval` in relevant test cases. This improves test reliability and consistency.
Affected files:
- test_staking_rewards.py
- test_committee.py
- test_constitution.py
- test_guardrails.py
- test_no_confidence.py
=> feat(tests): add wait_for_epoch_interval for vote timing

cardano_node_tests/tests/tests_conway/test_conway.py
Add tests to verify behavior when submitting or building transactions with an unregistered deposit return address in the Conway era. Includes scenarios for both `transaction build-raw` and `transaction build` commands, and for both `transaction submit` and submit-api REST service..
=> feat(tests): add tests for unregistered deposit return address

cardano_node_tests/tests/common.py, cardano_node_tests/tests/test_node_upgrade.py, cardano_node_tests/tests/tests_conway/conway_common.py, cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_conway/test_constitution.py, cardano_node_tests/tests/tests_conway/test_drep.py, cardano_node_tests/tests/tests_conway/test_guardrails.py, cardano_node_tests/tests/tests_conway/test_hardfork.py, cardano_node_tests/tests/tests_conway/test_info.py, cardano_node_tests/tests/tests_conway/test_no_confidence.py, cardano_node_tests/tests/tests_conway/test_pparam_update.py, cardano_node_tests/tests/tests_conway/test_treasury_withdrawals.py, cardano_node_tests/tests/tests_conway/test_update_plutusv2_builtins.py
- Introduced `get_registered_pool_user` in `common.py` to create and register pool users.
- Removed duplicate implementation of `get_registered_pool_user` from `conway_common.py`.
- Updated references in tests to use the new utility in `common.py`.
This change improves code reuse and simplifies pool user creation.
=> feat(common): move `get_registered_pool_user` utility

cardano_node_tests/tests/test_delegation.py, cardano_node_tests/utils/clusterlib_utils.py
Refactor stake address registration and deregistration logic to use utility functions in `clusterlib_utils`. This improves code reusability and readability across tests.
=> feat: use utility functions for stake address management

.github/workflows/regression_reusable.yaml
Updated the environment variable name from CLI_REV to CARDANO_CLI_REV in the regression reusable workflow. The CARDANO_CLI_REV is the correct name expected by `regression.sh`.
=> fix(workflow): rename CLI_REV to CARDANO_CLI_REV in env file

cardano_node_tests/tests/test_governance.py, cardano_node_tests/utils/poll_utils.py
- Updated `test_governance.py` to use "compatible" group in CLI checks.
- Removed `@pytest.mark.smoke` from polls test cases.
- Modified `poll_utils.py` to use "compatible" group in CLI commands for poll creation, answering, and verification.
=> feat(governance): use poll commands from `compatibile`

.github/regression.sh, README.md
Document how to use custom `cardano-cli` and `cardano-node` binaries during test runs.
Updated `.github/regression.sh` to detect and warn about binaries in the `.bin` directory.
Added documentation to `README.md` on how to use this feature.
=> feat: document support for custom binaries in tests

cardano_node_tests/tests/tests_conway/test_conway.py
Update test_conway.py to account for the
ProposalReturnAccountDoesNotExist error in node versions <= 10.1.4.
This ensures compatibility with older node versions by adding an additional condition to the assertion in the test.
=> fix(tests): handle ProposalReturnAccountDoesNotExist error

cardano_node_tests/tests/test_governance.py
Updated the error message in `test_governance.py` to reflect the correct command syntax for `cardano-cli compatible babbage governance`. This ensures clarity when the poll commands are unavailable.
=> fix(tests): update governance poll error message

cardano_node_tests/utils/testnet_cleanup.py
Enhance the re-registration process for stake addresses by adding a retry mechanism. The function now waits for new blocks and retries querying stake address info up to three times. This ensures better handling of potential delays in stake address updates.
Additionally, updated log messages for better clarity and debugging.
=> fix(testnet_cleanup): improve stake addr re-registration

cardano_node_tests/tests/common.py
Enhance funding-related functions by introducing `name_template` and `tx_name` parameters. These changes improve traceability and customization for transactions and address creation.
- Updated `detect_fork` to use `tx_name` and modified `name`.
- Added `name_template` parameter to `_get_funded_addresses`.
- Passed `name_template` and `tx_name` to relevant calls in `get_payment_addrs` and `get_pool_users`.
=> feat(tests): add name_template and tx_name for funding

src_docs/source/test_results/node/tag_10_2_1.rst, src_docs/source/test_results/tag_tests.rst
- Introduced a new documentation file for test results of node tag 10.2.1.
- Included regression, upgrade, rollback, and reconnection testing details.
- Updated `tag_tests.rst` to reference the new test results file.
=> feat(docs): add test results for node tag 10.2.1

cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster, cardano_node_tests/cluster_scripts/testnets/start-cluster
Add the `--output-text` flag to `cardano-cli query utxo` commands in cluster scripts to ensure consistent output format.
=> feat(cluster-scripts): add --output-text to query utxo

poetry.lock, pyproject.toml
Updated cardano-clusterlib dependency from version 0.7.5 to 0.7.6.
=> chore(deps): bump cardano-clusterlib to 0.7.6

cardano_node_tests/tests/test_cli.py
The --output-text option was added to the "transaction calculate-min-fee" command invocation. This ensures the output format is text even though JSON is now the default output.
=> feat(cli): ensure text output

cardano_node_tests/tests/test_native_tokens.py
Updated the error message assertion in `TestTransfer` to account for the new error message format introduced in node 10.4.0. The assertion now supports both the new and old error messages, ensuring compatibility across versions.
=> fix(tests): update error message assertion for node 10.4.0+

cardano_node_tests/cardano_cli_coverage.py, cardano_node_tests/chang_us_coverage.py, cardano_node_tests/defragment_utxos.py, cardano_node_tests/dump_requirements_coverage.py, cardano_node_tests/prepare_cluster_scripts.py, cardano_node_tests/split_topology.py
Simplified the logging configuration in multiple scripts by removing the redundant `%(name)s` field from the log format. This change ensures a more concise and consistent log output.
=> refactor(logging): simplify logging format configuration

.github/workflows/regression_reusable.yaml
Updated the mail failure report step in the regression workflow to only send emails when triggered by a scheduled event. This prevents unnecessary emails for other event types.
=> fix(workflow): restrict failure emails to scheduled events

.github/workflows/upgrade_reusable.yaml
Updated the mail failure report step to only send emails when the workflow is triggered by a scheduled event. This prevents unnecessary emails for other event types.
=> feat(workflow): restrict failure emails to scheduled upgrade tests

cardano_node_tests/cluster_scripts/conway/start-cluster
Switch to the "legacy" genesis command to address an issue where the "latest" command generates 185 entries for the PlutusV2 cost model instead of the expected 175 entries.
=> fix(cluster): use legacy genesis command for Conway cluster

cardano_node_tests/tests/issues.py, cardano_node_tests/tests/test_tx_basic.py
- Introduced a new blocker `api_829` for tracking the issue related to wrong autobalancing when there's no change in transactions.
- Updated `TestBasicTransactions` to handle the specific error message for minimum UTxO threshold.
The API issue: https://github.com/IntersectMBO/cardano-api/pull/829
=> feat(tests): add handling for API issue 829

src_docs/source/test_results/nightly_system_tests.rst
Updated the description of the network topology in the nightly system tests documentation from "default (legacy)" to "legacy" as p2p is now the default.
=> docs(nightly-tests): update network topology description

cardano_node_tests/utils/gh_issue.py
Updated the GitHub authentication method to use `github.Auth.Token` when a token is provided. This ensures compatibility with the latest GitHub API changes.
=> fix(utils): update GitHub auth method for token usage

cardano_node_tests/utils/submit_api.py
- Increased HTTP request timeout from 20 to 60 seconds.
- Simplified retry logic by removing unnecessary delay flag.
- Added a final error raise if all attempts fail to submit the transaction.
These changes enhance the robustness of transaction submission by providing better retry handling and clearer error reporting.
=> feat(submit-api): improve retry logic and timeout handling

cardano_node_tests/cluster_scripts/conway/cardano-node-bft1, cardano_node_tests/cluster_scripts/conway/start-cluster, cardano_node_tests/cluster_scripts/conway/template-cardano-node-pool, cardano_node_tests/cluster_scripts/conway_fast/cardano-node-bft1, cardano_node_tests/cluster_scripts/conway_fast/start-cluster, cardano_node_tests/cluster_scripts/conway_fast/template-cardano-node-pool, cardano_node_tests/cluster_scripts/mainnet_fast/cardano-node-bft1, cardano_node_tests/cluster_scripts/mainnet_fast/start-cluster, cardano_node_tests/cluster_scripts/mainnet_fast/template-cardano-node-pool
The UTXO backend configuration now happens in node config.
Updated jq commands to dynamically set `LedgerDB.Backend` based on the backend type (`mem`, `disk`) or remove it if not applicable.
=> feat(utxo-hd): update UTXO backend configuration

.github/workflows/regression-dbsync.yaml, .github/workflows/regression.yaml, .github/workflows/regression_reusable.yaml
Added a new input parameter `utxo_backend` to the regression workflows (`regression-dbsync.yaml`, `regression.yaml`, and
`regression_reusable.yaml`). This parameter allows specifying the UTxO backend with options `mem` or `disk`.
=> feat(workflows): add utxo_backend input to workflows

.github/workflows/regression-dbsync.yaml, .github/workflows/regression.yaml
Added an empty string option to the UTxO backend choice in both `regression-dbsync.yaml` and `regression.yaml` workflows. This ensures that users can explicitly select no backend if needed.
=> feat(workflows): add empty option for UTxO backend choice

cardano_node_tests/tests/test_pools.py
Match the new error message in CLI master as well as the "old" one in the released CLI.
=> fix(tests): match also new error message

.github/node_upgrade.sh
The directory listing command was unnecessary and has been removed to streamline the script. This change reduces noise in the output and improves script clarity.
=> chore(ci): remove redundant directory listing in script

cardano_node_tests/tests/common.py
Updated the random string length from 3 to 6 characters in the `get_test_id` function to enhance uniqueness of generated test IDs. This change ensures better differentiation between test runs.
=> feat(common): increase random string length in test ID

.github/regression.sh, README.md, cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/utils/configuration.py
- Added a check to ensure the number of running tests on a cluster instance does not exceed the configured maximum (`MAX_TESTS_PER_CLUSTER`).
- Introduced a new configuration variable `MAX_TESTS_PER_CLUSTER` with a default value of 10, which can be overridden via environment variables.
- Updated logic in `ClusterGetter` to handle cases where the limit is reached by introducing a delay and skipping further processing for the affected cluster instance.
=> feat(cluster): enforce max tests per cluster instance

cardano_node_tests/tests/conftest.py, cardano_node_tests/utils/configuration.py
Add `CLUSTERS_COUNT` and `MAX_TESTS_PER_CLUSTER` to pytest configuration stash for better test metadata tracking.
=> feat(configuration): add cluster info metadata

cardano_node_tests/tests/test_governance.py
Updated the `governance_poll_available` fixture to use `pytest.xfail` instead of `pytest.fail` for better handling of unavailable poll commands. This ensures tests are marked as expected failures rather than hard failures.
=> refactor(tests): replace pytest.fail with pytest.xfail

cabal_build_tests/fedora/Dockerfile, cabal_build_tests/install-node.sh
- remove manual `pkgconf` build
There is no need to download and build manually `pkg-config` on `Fedora` anymore as it is already updated: https://packages.fedoraproject.org/pkgs/pkgconf/pkgconf-pkg-config/
- update GHC to `9.6.7` and Cabal to `3.12.1.0` - so tests use the same versions as in recently updated instruction: https://github.com/cardano-foundation/developer-portal/commit/7edb2750563af45e6e6160a39714ad78fc843bb0
=> Cabal build tests - Remove manual pkgconf build and update GHC and Cabal

cardano_node_tests/tests/test_pools.py
Replace deprecated usage of `get_pool_params` with `get_pool_state`.
=> fix(pools): use get_pool_state instead of get_pool_params

poetry.lock
Upgraded setuptools from version 75.5.0 to 80.7.1 in poetry.lock.
setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write. A path traversal vulnerability in PackageIndex was fixed in setuptools version 78.1.1
Reference:
<https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5>
=> chore(deps): update vulnerable setuptools to v80.7.1

.github/create_results.sh
Update `.github/create_results.sh` to correctly check for the presence of JSON report files before proceeding. Separate `mv` commands for `.json`, `.txt`, and `.properties` files now handle missing files gracefully by redirecting errors to `/dev/null`. This prevents script failures when some optional report file types are absent.
=> fix(ci): handle missing report files in results script

src_docs/source/test_results/node/tag_10_2_1.rst, src_docs/source/test_results/sync_tests.rst
- Updated the mainnet sync test link in `tag_10_2_1.rst` to point to the published Google Docs version.
- Refactored `sync_tests.rst` for clarity:
- Improved introduction and test descriptions.
- Replaced raw HTML dashboards with a list of published sync test result documents for recent cardano-node releases.
- Added repository link for source code reference.
=> docs(sync-tests): update sync test links and improve docs

.github/node_upgrade_pytest.sh
Update the node upgrade pytest script to use 'latest' instead of 'legacy' when calling `cardano-cli genesis hash` for Alonzo and Conway genesis files.
=> fix(ci): use 'latest' instead of 'legacy' for genesis hash

cardano_node_tests/tests/test_tx_basic.py
Add assertion to check that the transaction build command's stdout contains Lovelace fee information. This ensures that fee details are present in the output, improving test coverage.
=> test(tx_basic): assert fee info in tx build stdout

cardano_node_tests/tests/issues.py, cardano_node_tests/tests/test_tx_basic.py
Add handling for CLI error when `build-estimate` fails to balance a transaction with no txouts, referencing issue IntersectMBO/cardano-cli#1199.
=> fix(issue): check issue for build-estimate failure with no txouts

cardano_node_tests/tests/test_blocks.py, cardano_node_tests/tests/test_node_upgrade.py, cardano_node_tests/tests/test_reconnect.py, cardano_node_tests/tests/test_rollback.py, cardano_node_tests/tests/test_tx_basic.py, cardano_node_tests/tests/test_tx_many_utxos.py, cardano_node_tests/tests/test_tx_mempool.py, cardano_node_tests/tests/test_tx_negative.py, cardano_node_tests/tests/tests_plutus_v2/test_spend_compat_raw.py
Renamed the variable `destinations` to `txouts` across multiple test files for consistency and clarity.
=> refactor: rename destinations to txouts in tests

.github/env_nightly_upgrade
Bump the BASE_TAR_URL in .github/env_nightly_upgrade to use the cardano-node 10.4.1 release instead of 10.3.1. This ensures nightly upgrade workflows test against the latest mainnet node release.
=> chore(ci): update cardano-node to 10.4.1 in nightly upgrade

cardano_node_tests/cluster_management/resources_management.py, cardano_node_tests/utils/custom_clusterlib.py, pyproject.toml
- Add "ANN" (type annotation) checks to ruff linting, except for test, framework, and docs files.
- Ignore ANN401 for ruff to allow untyped self/cls.
- Remove mypy per-file overrides for untyped defs in tests and framework.
- Add explicit return types to __init__ methods in resource and clusterlib.
=> chore(lint): enforce type annotations using ruff instead of in mypy

.github/node_upgrade_pytest.sh, .github/stop_cluster_instances.sh, cardano_node_tests/cluster_scripts/common/start-cluster-fast, cardano_node_tests/cluster_scripts/conway_slow/start-cluster, cardano_node_tests/cluster_scripts/testnets/start-cluster, cardano_node_tests/utils/cluster_scripts.py, scripts/restart_dev_cluster.sh
Renamed the cluster stop script from `supervisord_stop` to `stop-cluster` across all relevant scripts and references. This improves naming clarity and consistency with other cluster management scripts. Updated all usages, checks, and permissions to use the new script name. No functional changes to cluster start/stop logic.
=> refactor(cluster): rename supervisord_stop to stop-cluster

cardano_node_tests/cluster_scripts/common/start-cluster-fast, cardano_node_tests/cluster_scripts/conway_fast/testnet.json, cardano_node_tests/cluster_scripts/conway_slow/start-cluster, cardano_node_tests/cluster_scripts/conway_slow/testnet.json, cardano_node_tests/cluster_scripts/mainnet_fast/testnet.json, cardano_node_tests/cluster_scripts/testnets/start-cluster, cardano_node_tests/cluster_scripts/testnets/testnet.json
Add `testnet.json` metadata files to each cluster script directory to describe the testnet setup and supported environment variables. Update cluster startup scripts to copy `testnet.json` to the state directory and create a `status_started` file as a marker when the cluster starts. Replace legacy PID file checks with socket existence checks for improved robustness. Also, update cluster start messages with a rocket emoji for clarity.
=> feat(cluster): add testnet.json metadata and status file

cardano_node_tests/cluster_scripts/common/start-cluster-fast, cardano_node_tests/cluster_scripts/conway_slow/start-cluster
Previously, the governance_data directory was created separately after initial cluster setup. This change moves its creation into the main directory setup step, ensuring it is always present and avoiding redundant mkdir calls.
=> refactor(cluster): create governance_data dir together

cardano_node_tests/tests/tests_conway/test_constitution.py
Increase a time in epoch in `wait_for_epoch_interval` by 20 seconds to ensure votes are submitted within the intended epoch window. This adjustment helps prevent timing issues during test execution.
=> fix(tests): increase a guaranteed time in epoch

testnets_bootstrap_template/README.md
Fixed typo. Updated the example NODE_REV in the test command from 8.0.0 to 10.4.1 to reflect the latest supported version.
=> docs(readme): update sync instruction and node version

.pre-commit-config.yaml
Move pyrefly hook before ruff formatter, because pyrefly can modify the code.
=> chore(pre-commit): reorganize config

cardano_node_tests/tests/tests_plutus/test_spend_negative_build.py, cardano_node_tests/tests/tests_plutus/test_spend_negative_raw.py
Expand hypothesis strategies in negative redeemer tests to sample from known non-int fields and arbitrary text, increasing coverage of invalid redeemer types. Add explicit assumption to skip "int" type. Update assertions to handle new error message variants for known fields.
=> feat(tests): improve negative redeemer fuzzing coverage

cardano_node_tests/tests/common.py
Moved the definition of PARAM_USE_BUILD_CMD below PARAM_OFFLINE_BUILD_METHOD and marked it as deprecated in favor of PARAM_BUILD_METHOD. This clarifies preferred usage and improves code organization. No functional changes made.
=> refactor(common): move and deprecate PARAM_USE_BUILD_CMD

cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_conway/test_constitution.py, cardano_node_tests/utils/dbsync_utils.py
Refactored dbsync_utils.check_epoch_state to use ActionTypes enum instead of string literals for action type. Updated all usages in committee and constitution tests. Added ActionTypes enum to dbsync_utils for clarity and type safety. Improved error handling for unsupported action types.
=> refactor: use enum for epoch state action type

.github/env_nightly_upgrade, flake.lock
Update .github/env_nightly_upgrade to use cardano-node 10.5.1 tarball. Ensures nightly upgrade and builds use latest upstream versions.
=> chore(deps): upgrade cardano-node to 10.5.1

cardano_node_tests/cluster_management/cluster_getter.py, cardano_node_tests/cluster_management/manager.py, cardano_node_tests/cluster_management/resources_management.py
Refactored code to replace assert statements with explicit exception raising for better error handling and clarity. Changed inappropriate asserts to TypeError or RuntimeError where applicable, and improved error messages for invalid input types and unexpected states.
=> refactor: replace asserts with explicit exceptions

cardano_node_tests/tests/tests_conway/test_committee.py
This PR updates  Committee Action tests to align with the unified transaction building approach. The redundant `use_build_cmd` parameter is replaced by `build_method`, ensuring consistency across all certificate submission flows.
* **Hot Key Registration Tests**
* Updated `test_register_hot_key_no_cc_member` to pass `build_method` instead of `use_build_cmd`.
* **Committee Action Tests**
* Updated `test_update_committee_action` and related committee tests.
* Removed direct `use_build_cmd` handling and replaced with `build_method`.
Test Run: https://github.com/IntersectMBO/cardano-node-tests/actions/runs/17410634762
=> This PR refactors test_committee to align with the new build Method

cardano_node_tests/tests/tests_conway/test_committee.py, cardano_node_tests/tests/tests_conway/test_treasury_donation.py
This PR updates the `test_transfer_treasury_donation` test to align with the ongoing transaction-building refactor. The `use_build_cmd` flag has been removed and replaced with the more explicit `build_method` parameter.
* **`test_transfer_treasury_donation`**
* Replaced `use_build_cmd` argument with `build_method`.
* Ensures treasury donation transactions follow the same unified build logic used in other tests.
* Consistency across all transaction-related tests.
* Simplifies test logic by removing redundant boolean flag.
* Aligns treasury donation flow with the unified `build_and_submit_tx` interface.
Test RUN: https://github.com/IntersectMBO/cardano-node-tests/actions/runs/17414430310
=> Build method test treasure donation

cardano_node_tests/utils/helpers.py, cardano_node_tests/utils/smash_utils.py
Refactored imports in helpers.py and smash_utils.py to use explicit collections.abc and requests.auth imports. This resolves pyright attribute access issues and improves type hinting compatibility.
=> fix(imports): improve pyright compatibility for helpers and smash

cardano_node_tests/tests/delegation.py, cardano_node_tests/tests/test_delegation.py
This PR simplifies and unifies the delegation transaction handling by removing redundant `use_build_cmd` branches and consolidating transaction creation into a single `clusterlib_utils.build_and_submit_tx` flow.
* **`delegate_stake_addr`**
* Removed conditional handling of `use_build_cmd` vs. `send_tx`.
* Replaced both with `clusterlib_utils.build_and_submit_tx` for consistency.
* Ensures returned `DelegationOut` uses `tx_output` instead of mixed outputs.
* Balance validation updated to reference unified transaction output.
* **`test_delegation.py`**
* Updated delegation tests (`delegate using pool_id`, `delegate using vkey`, `delegation + deregistration`, `unknown addr`, `deregistered addr`) to use `build_method` instead of `use_build_cmd`.
* Simplified test logic by removing duplicated …
=> This PR refactors test_delegation to align with the new build Method

cardano_node_tests/cluster_scripts/testnets/start-cluster
Add a check to ensure the script is not run from the state directory, which will be deleted during execution. Improve error handling for removal of the state directory, exiting with a message if deletion fails.
=> fix(start-cluster): handle state dir deletion errors

cardano_node_tests/tests/tests_conway/test_info.py
Updated test_info to replace deprecated use_build_cmd=True with build_method=BuildMethods.BUILD for both proposal submission and vote submission. Keeps behavior identical while aligning with the new transaction-building interface.
=> This PR refactors test_info.py align with the new build Method
